### ISSUE TITLE
[BUG] Infinite looping when launching the app, happening on occasion

### ISSUE THREAD

**Issue by Alex-NRCan** [Canadian-Geospatial-Platform/geoview#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Sometimes**, upon launching the web application, the system enters an infinite loop of tile requests. It can be noticed by the times on the west side of Canada being blurred (as seen in the yellow square in the screenshot below) and by opening the Chrome network tab and looking at the requests happening. The screenshot below shows the network tab after 1 min after launch. Many tiles are requested more than once, 4022 requests were made, about 40MB were downloaded. 
![image](https://user-images.githubusercontent.com/94073946/234307709-411ae31f-09bc-4b75-b2bc-051863ffbbc2.png)

This additional screenshot below shows the state after 7.5 minutes, over 10,000 requests were made for the same tiles(!):
![image](https://user-images.githubusercontent.com/94073946/234308249-6625d779-d58d-48e2-94c9-168ba5ede000.png)

### Expected Behavior

Each tile is requested only once.

### Steps To Reproduce

My initialization config is below, but **this behavior doesn't happen all the time(!)**:
```
const map_config = {
	'map': {
		'interaction': 'dynamic',
		'viewSettings': {
			'zoom': 4,
			'minZoom': 2,
			'maxZoom': 12,
			'center': [-100, 60],
			'projection': 3978
		},
		'basemapOptions': {
			'basemapId': 'simple',
			'shaded': true,
			'labeled': false
		},
		'listOfGeoviewLayerConfig': []
	},
	'theme': 'dark',
	'components': ['app-bar', 'nav-bar', 'north-arrow', 'overview-map', 'footer-bar'],
	'corePackages': ['layers-panel'],
	'suportedLanguages': ['en', 'fr']
};
```

*EDITED*: to remove the listOfGeoviewLayerConfig array values which are outside the scope for this issue

**Comment by jolevesq** [comment]
We can try to use https://openlayers.org/en/latest/apidoc/module-ol_layer_Group-LayerGroup.html to let OpenLayers know these 3 layers are working together. We can maybe work with z-index to specify order.
