### ISSUE TITLE
[BUG] Details and data not unpacking clusters

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on a cluster, none of the features in it are displayed in the details panel, and the data panel does the same. Possibly from PR #930 in abstract-geoview-layer.ts

### Expected Behavior

When clicked on, the cluster in the details panel should be clickable to display the features it contains. Data should not show clusters.

### Steps To Reproduce

At https://canadian-geospatial-platform.github.io/geoview/public/package-footer-panel.html#HUC3 check data panel in footer panel, and click on any cluster.

**Comment by jolevesq** [comment]
Cluster are not supported anymore
