### ISSUE TITLE
[UPDATE] Update MUI to latest version

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

MUI is now at version 6. Update packages.json and looks for side effect in our components. Some properties are deprecated like components on data-grid components

**Comment by cphelefu** [comment]
@jolevesq version 6 is still in pre-release. Its not a stable version yet. We may want to wait until it is stable.
