### ISSUE TITLE
[BUG] footer-panel not loading on languages.html in edge

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

One or both footer-panels fail to load on languages.html, and then generate an error message when trying to access panel. Happens in edge, could not duplicate in chrome. package-footer-panel.html is working fine.

### Expected Behavior

Should load properly.

### Steps To Reproduce

In edge, go to https://canadian-geospatial-platform.github.io/geoview/public/package-footer-panel.html - check if both footer-panels have loaded.

**Comment by DamonU2** [comment]
This is due to class="llwp-map" being added to the LNG1 div. createMapFromConfig is meant to create a map in non map div.

**Comment by jolevesq** [comment]
This as been resolve by another PR. Some bug still there with config but will be resolve by language broken PR
