### ISSUE TITLE
[BUG] Unclustered points cluster when zooming out

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If clustering is toggled off on a layer, the layer is then zoomed in past the splitZoom value, and then zoomed out beyond the splitZoom value, the points cluster.

### Expected Behavior

If clustering is toggled off, should remain off until toggled on.

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/cluster.html and toggle a layers clustering off, zoom in close, and zoom out.

**Comment by jolevesq** [comment]
We removed clustering
