### ISSUE TITLE
[Improvement] Optimize footer panel - Details tab

### ISSUE THREAD

**Issue by kaminderpal** [Canadian-Geospatial-Platform/geoview#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when we add `footer-tabs` component on map, it make Map/whole app very slow to operate. We need to optimize the footer-bar/tab's performance for details tab.

### Expected Behavior

n this ticket we need optimize the performance of Details Component. Opening of details tab  should be smooth and their should be no slowness/lag when click on details tab.

Add performance enhancement react hooks like useMemo, useCallback if required.

### Steps To Reproduce

1) Open http://localhost:8080/package-footer-panel.html
2) Click on details tab underneath map.
3) Observe the slowness on while show/hide of this tab.

**Comment by amir-azma** [comment]
We can close this issue as some optimization has been added related to loading footer bar/tab and details tab while we were working on other issues. Opening details tab is now smooth with no slowness/lag when click on different points on the map.

**Comment by amir-azma** [comment]
We can close this issue as some optimization has been added related to loading footer bar/tab and details tab while we were working on other issues. Opening details tab is now smooth with no slowness/lag when click on different points on the map.
