### ISSUE TITLE
[FEATURE] When feature is selected on map, highlight it in details panel

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

Once a feature is selected on the map, it should be highlighted in the details panel so it is obvious which details go with it.

**Comment by jolevesq** [comment]
Should be same thing from data-grid (checkbox) feature row. For details, it should be the other way around to. The open details item is highlighted on the map.
