### ISSUE TITLE
[REFACTOR] Layers-Panel is not using legendfeatureset

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Layers panelis not using the legendlayerset. It is relying on other events/

### Expected Behavior

Use the GeoView legendlayer set who is managing add/remove layers

### Anything else?
Solve
/home/runner/work/geoview/geoview/packages/geoview-layers-panel/src/panel-content.tsx
Warning: 8:3 warning 'payloadIsALayerConfig' is defined but never used @typescript-eslint/no-unused-vars
Warning: 9:3 warning 'payloadIsRemoveGeoViewLayer' is defined but never used @typescript-eslint/no-unused-vars

**Comment by DamonU2** [comment]
This is probably causing a bug on https://canadian-geospatial-platform.github.io/geoview/public/package-layers-panel.html - If you remove a layer from the second map and then open the legend, the map crashes.
