### ISSUE TITLE
[FEATURE] Circular Progress

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a developer, I would like to hide the viewer behind circular progress until pieces are available.

### Implementation UI

I has been removed with improve loading time PR. It use to work with layer loaded. We need to modify this and work with plugin ready. If we look at footer-panel html demo, the maps loads faster then the footer panel and it looks weird.

**Comment by DamonU2** [comment]
Additionally, add a small loading indicator if layers are still loading once the plugins are ready and the map is visible.
