### ISSUE TITLE
[FEATURE] Raw MUI DataTable

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a developer, I would like to be able to build raw datatable to easily asses problem and performance.

### Implementation UI

On datatable-panel.html page, add button to read the feature from URL below and create the datatable in standard div on the map.
[JSON Feature](https://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCC/Geochronology/MapServer/0/query?f=json&where=OBJECTID+%3E+0&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&having=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&f=html)

For this issue we will use the MUI data-grid component. We will use the features coming from the url and fake create the object needed (formatted as it is right now) to create the simple datatable.  The function from api datatable must take the value of one object and create table for it.

From this we will help to build the getAllFeatureInfo LayerSet

**Comment by kaminderpal** [comment]
Doesn't required as we are transition to Material React table
