### ISSUE TITLE
[BUG] Set Queryable = False Not Working

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we set queryable false for a layer, it is not working. It is still in the FeatureInfoLayerSet with items inside.

At the same time hover is adding a tooltip even when we are over a nav bar button or overview map on the map.
 

### Expected Behavior

If false, the items array for this layer in the FeatureInfoLayerSet should be empty.  The layer can still be in featureInfoLayerSet but with state disable and no item. From details interface we may turn on/off the capacity.

Hover tooltip should not appears or disappears when we hover element on the map.

### Steps To Reproduce

1. On any page with details enable, set the layer to be queryable false
2. Hover or click on the layer, hover appears and click will add info in details panel

**Comment by DamonU2** [comment]
Seems to be working now, layer types return empty array, and no tool-tip or details
