### ISSUE TITLE
[FEATURE] Add alias paths and reduce the use of relative paths.

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1174]
**Is there an existing issue for this?**
Nope

**Who request this Feature**
Development team

**User Story**
Throughout the application we are using relative paths in our import statements, e.g. `import { EVENT_NAMES } from '../../../api/events/event-types'`.
We need to add alias paths so we can change paths to `import { EVENT_NAMES } from '@/api/events/event-types'`.

We can use [webpack alias path](https://webpack-v3.jsx.app/configuration/resolve/).

**Additional context**
We can add the following paths.

```
alias: {
  @: path.resolve(__dirname, 'src'),
  @api: path.resolve(__dirname, 'src/api/')
  @core: path.resolve(__dirname, 'src/core/')
  @ui: path.resolve(__dirname, 'src/ui/')
  @geo: path.resolve(__dirname, 'src/geo/')
}
```

**Comment by jolevesq** [comment]
That is a good idea. Will have a minor modification on almost all files. Just to need to find the best time to do it.
