### ISSUE TITLE
[FEATURE] Replace snackbar alerts with notifications.

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Christopher Phelefu

### User Story

Replace snackbar notifications with notification center located in the app-bar at the bottom.

**Comment by jolevesq** [comment]
We should replace npm snackbar by MUI snackbar. Just add a smalll messsage to it and the longer one in notification. Maybe blink the button on new notification as well.

**Comment by Alex-NRCan** [comment]
@jolevesq @cphelefu

I have also made some code in the [utilities.showMessage](https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/core/utils/utilities.ts#L58) functions to be able to show a message (snackbar) with or without a notification if this can be beneficial, I can create a PR with it.
It basically allows to either:
- show a snackbar message
- add a notification
- or both show snackbar message and add notification

The code examples can be found in my fork here:
add a notification: https://github.com/federal-geospatial-platform/geoview_core/blob/develop/packages/geoview-core/src/core/utils/utilities.ts#L58
show a message and a notificaiton at the same time: https://github.com/federal-geospatial-platf
orm/geoview_core/blob/develop/packages/geoview-core/src/core/utils/utilities.ts#L122

**Comment by jolevesq** [comment]
@cphelefu I think we will keep both ways and with the new functions added by Alex, it will be more customizable. We will move to MUI snack bar but keep both of them./.. snack bar and notification.
