### ISSUE TITLE
Geocore layer signal processed before time

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/geoview#1214]
Geocore is a layer that mutate to a different GeoView layer. The processed signal is signal at the end of the Geocore layer processing, but the new mutant layer process is not completed.. We need to pastpone the signal to the end of the new layer process.

**Comment by jolevesq** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/1214?planning-poker) with Zenhub @ychoquet
