### ISSUE TITLE
[BUG] Once page loads, clicking on a point on layer opens Legend tab for a second

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once we load a page with map and layers, if we click on a point on the map, the Legend tab will be loaded for a short time about 1 second, and then the details tab opens.

**Note**: It seems this happens only when the page loads and occurs only on the first click, but after that works fine. 
In video below, once I click on the circle on the map, the Legend tab opens for a short time.

https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/42d04f76-65e0-4492-ae6c-0660d0f55768

### Expected Behavior

Clicking on a point should open straight to the details. Legend tab should not open once we click on the map.

### Steps To Reproduce

Refer to uploaded video.

**Comment by jolevesq** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/1241?planning-poker) with Zenhub @amir-azma @DamonU2 @cphelefu @kaminderpal

**Comment by jolevesq** [comment]
Solved by PR setting the tabs open by default
