### ISSUE TITLE
[New Legend] Implement ability to remove legend item

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Christopher Phelefu

### User Story

Implement ability to remove legend item.
We are missing the UI for this.

**Comment by jolevesq** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/1255?planning-poker) with Zenhub @amir-azma @cphelefu @kaminderpal
