### ISSUE TITLE
[FEATURE] add ability to highlight layer or sublayer on map

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

OSDP?

### User Story

Came up during Vlad's UI demo. Users would like the ability to highlight an entire layer or sublayer on the map. The current feature highlight animation is not ideal, it is too flashy for an entire layer. Perhaps a the same look (white outline, translucent white fill) without the animation would work.

**Comment by jolevesq** [comment]
The highlight should maybe blur all other layers and display the highlighted layer on top (like in RAMP)
