### ISSUE TITLE
[FEATURE] Implement the group icon (stack of icons) component

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

Currently, in legend tab we show a group of icons on the left hand side of layer list (screenshot below). 
We need to have a stand alone component for this feature, so we can also display the group of icons in Details tab in layer list.

Review the existing functionality and try to have it as a separate component, might need some cleaning or optimization.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/f511eb22-7b7d-4a8a-aedc-2dc78f29227e)

**Comment by jolevesq** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/1305?planning-poker) with Zenhub @amir-azma @cphelefu @kaminderpal @DamonU2
