### ISSUE TITLE
[BUG] notifications and about cause error when using keyboard focus

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Enabling keyboard focus and interacting with the notifications or about causes `Uncaught RangeError: Maximum call stack size exceeded.` and pressing enter on another button does not remove the popup.

### Steps To Reproduce

1. On https://canadian-geospatial-platform.github.io/geoview/public/add-panels.html press tab until the popup appears for keyboard navigation and enable it.
2. Tab until you get to the about or notification button, tab away and error occurs.

**Comment by jolevesq** [comment]
Close as part of https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523
