### ISSUE TITLE
[FEATURE] Create learn more component

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

We need to have a "Learn More" component that it can be either a hyperlink or a popover that can be used in other places.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/8b9b6472-3a4f-4a89-bbb1-8f0398c7c07e)

**Comment by jolevesq** [comment]
Done with Guide TAb
