### ISSUE TITLE
Plugins refactoring

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/geoview#1336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The reload function used in the Language.html template has a problem with plugins. The current implementation deals globally with the definition of plugins, but on some occasions the code treats them as part of a map. This is problematic when there are several maps.

### Expected Behavior
Plugins must be taken into account per map, and they must be independent of those present on other maps.

### Steps To Reproduce

In the current environment, run the Languages.html template and trace the code to see how the reload function treats plugins as a whole in some cases and individually per map in others.

**Comment by jolevesq** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/1336?planning-poker) with Zenhub @ychoquet

**Comment by Alex-NRCan** [comment]
My understanding is that:
- window.plugins[pluginId] refers to the 'class definition'. It's the geoview-{pluginId}.js script file that gets injected in the dom tree.
- cgpv.api.plugins[mapId][pluginId] refers to the class instance and that one is per-map.

Unless there's something else this issue should be encompassing, it can probably be closed.
