### ISSUE TITLE
[BUG] Invalid Layer Status

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/geoview#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest modification to the `layerStatus `property domain has introduced a bug in the viewer. Not all WMS layers end with a `'loaded'` status. This is because the code that assigns this value to the layerStatus property does not take layer groups into account. In addition, the new domain makes the `'processed'` value obsolete. Consequently, this value should be removed from the domain.

### Expected Behavior

 If `'loaded'` is the value we want to use to signal that the loading process is complete, the code managing the status should be removed from the `Layer` class and moved just after the creation of the `gvLayer` property of the displayable layers (the leaves layer). For example, the code of the WMS type leaves (in the wms.ts file) should look like this:

```
          layerEntryConfig.gvLayer = new ImageLayer(imageLayerOptions);

          let imageloaderrorHandler: () => void;
          const imageLoadEndHandler = () => {
            api.event.emit(
              LayerSetPayload.createLayerSetChangeLayerStatusPayload(this.mapId, Layer.getLayerPath(layerEntryConfig), 'loaded')
            );
            layerEntryConfig.gvLayer!.get('source').un('imageloaderror', imageloaderrorHandler)
          };
          imageloaderrorHandler = () => {
            api.event.emit(
              LayerSetPayload.createLayerSetChangeLayerStatusPayload(this.mapId, Layer.getLayerPath(layerEntryConfig), 'error')
            );
            layerEntryConfig.gvLayer!.get('source').un('imageloadend', imageLoadEndHandler)
          };

          layerEntryConfig.gvLayer.get('source').once('imageloadend', imageLoadEndHandler);
          layerEntryConfig.gvLayer.get('source').once('imageloaderror', imageloaderrorHandler);

```
This modification must be applied to all GeoView layer types and must take into account the kind of layer (image, vector, tile).

### Steps To Reproduce

In the current environmnet, run the test.html template and you should see that the two first WMS that are part of a group end with a **_processed_** status instead of **_loaded_**

**Comment by jolevesq** [comment]
May be related to the issue with the swiper and WMS
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/3472990/4ecc5622-318f-4ddd-949b-e77f5dbb6775)
