### ISSUE TITLE
[REFACTOR} Remove Init

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1374]
Remove init function from our caode base and samples. For the moment, the viewer need this init function to start process and let the user listen for the reday from the api. We should use the api event loaded to listen that map is reday fromt eh html page

**Comment by ychoquet** [comment]
After analyzing the problem, we came to the conclusion that the init function is the simplest way to signal to users that all the async processing required to initialize and load map layers has been completed. As a result, the init function will not be removed.
