### ISSUE TITLE
[BUG] Swiper is over footer-bar

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The swiper is set in the div containing the footer-bar, instead of just the map, this leads to an offset of the layers shown/hidden.

### Expected Behavior

Swiper should be in the map div and properly divide layers

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/package-swiper.html and look at the first map

**Comment by jolevesq** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/1404?planning-poker) with Zenhub @amir-azma @cphelefu @DamonU2 @kaminderpal
