### ISSUE TITLE
[BUG] map and footer-bar extend out of div at certain sizes

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At certain sizes (between a window size of about 960-1090 pixels) the map and footer-bar extend outside of the div containing them, which cuts off the overview-map and footer-bar. This also causes some shaking when mousing over the map.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/63123585/2c780809-3e89-46d1-8fe1-f110963cdc61)

**Comment by jolevesq** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/1406?planning-poker) with Zenhub @amir-azma @cphelefu @DamonU2 @kaminderpal
