### ISSUE TITLE
[BUG] [FEATURE] Legend: When a legend item is open (been clicked on) - its icon dissapears

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an legen item is clicked on - its icon dissapears.

### Expected Behavior

The icon is not supposed to dissapear.

### Steps To Reproduce

1. In the new legend, 
2. click one of the legend items
3. Notice the icon on the left

**Comment by jolevesq** [comment]
Because we have left/right panel with clear purpose, I do not think we have to remove the icon stack when layer is selected. We may want to validate with @vgulyy .
