### ISSUE TITLE
[FEATURE] Package Skeleton for Geoview Chart

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1419]
Make the first push to Geoview repo with the new geoview-chart package

**Comment by Alex-NRCan** [comment]
The PR is ready and constantly updated until it's merge officially.

https://github.com/Canadian-Geospatial-Platform/geoview/pull/1444

**Comment by DaKinMan** [comment]
I believe this can be officially closed now.

**Comment by jolevesq** [comment]
Merged
