### ISSUE TITLE
[FEATURE] Create JSON Schema for chart

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1420]
Create the JSON schema who will be use to configure the package. Schema can be inspired by https://github.com/fgpv-vpgf/contributed-plugins/tree/master/chart.

- LayerID
- FieldName
- LinkTable URL
- FieldLinkTable
- FieldsLinkValues []
- Chart type, title
- Axis type, labels, slider
- Color

We should aim to have a schema cleaner then the previous plugin for RAMP.

**Comment by Alex-NRCan** [comment]
The JSON schema is pretty advanced as of Nov. 3rd. I'm testing various usecases and it supports them so far.

I'm assuming we can close this issue for now? Or do we want to make sure ALL usecases are supported before we actually solidify/finalize the schema?

**Comment by jolevesq** [comment]
Not all but if we covers the bullets point, we can close
