### ISSUE TITLE
[FEATURE] Create GeoJSON Sample Dataset

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1421]
We should create fake dataset to demo our 4 supported type charts (line, bar, pie and donought.

For line, we can reuse a real dataset provided by HC https://search.open.canada.ca/openmap/21b821cf-0f1c-40ee-8925-eab12d357668
- Layer: https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/airborne_radioactivity_en/MapServer/2
- Link table: https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/airborne_radioactivity_en/MapServer/3

**Comment by Alex-NRCan** [comment]
I've implemented support for that kind of layer with a related table.
