### ISSUE TITLE
[FEATURE] Refactor focus button for the best solution 

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

We have added 3 focus buttons that we need to make a decision which one we need to keep on the page/map. 

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/bd03e2e4-788b-4dec-93e9-6922b2908045)

**Comment by jolevesq** [comment]
@amir-azma please ask for a vote in geoview channel and we will choose an option
