### ISSUE TITLE
[BUG] Details not opening when feature is clicked on the map

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on a map feature, the details panel does not open automatically.

### Expected Behavior

Clicking on feature should automatically open details panel in footer-bar.

### Steps To Reproduce

Got to any map with details in footer-bar
Click on a feature

**Comment by jolevesq** [comment]
Si details est ouvert on reste sur details, si chart est ouvert on reste sur chart. Si un autre est ouvert, on va versle dernier qui etait ouvert (details ou chart). Ou on fait plus simple, toujours sur detail si chart est pas actif

**Comment by jolevesq** [comment]
Done with another PR
