### ISSUE TITLE
[BUG] Clicking on a feature on the time-slider map causes a crash

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a feature is clicked on the time-slider map, the map crashes and gives: TypeError: Cannot read properties of null (reading 'ol_uid')

**Comment by jolevesq** [comment]
This type of errors occurs often, we will need to find the root cause
