### ISSUE TITLE
[BUG] fullscreen black loading screen on page load while maps are loading

### ISSUE THREAD

**Issue by PVautour** [Canadian-Geospatial-Platform/geoview#1481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When loading a page with a map on it, a seems a big black loading screen overlays the whole page. 

This flashes once for each map loaded. A dozen maps will reset the animation 10 times before letting it resolve. (technically it might be spawning a dozen overlays but it hard to tell).

### Expected Behavior

The loading overlay is only over the map section and doesn't impede on the rest of the web page. 

### Steps To Reproduce

1. got to [this url](https://dki8ekjjwh11o.cloudfront.net/fr-ca/map-browser).
2. refresh the page.
3. see the black loading screen.

### Anything else?

The code to the front-end using the maps is [here](https://github.com/Canadian-Geospatial-Platform/app.geo.ca-v2/tree/feature/search-result-map).

**Comment by DamonU2** [comment]
New url - https://d2cv8c9ti3iyv0.cloudfront.net/fr-ca/map-browser

**Comment by jolevesq** [comment]
Not
