### ISSUE TITLE
[BUG] error when navigatin off the page. DOMException: Node.removeChild: The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by PVautour** [Canadian-Geospatial-Platform/geoview#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When navigating off the page, an error occurs in the console for each map on the page:

```
DOMException: Node.removeChild: The node to be removed is not a child of this node
```

this causes cgpv to bug out and makes it so that polygons are no longer loaded on the map when traveling back to the page.

### Expected Behavior

cgpv does not throw an error when navigating off the page and reloads properly when i visit back.

### Steps To Reproduce

1. got to [this url](https://dki8ekjjwh11o.cloudfront.net/fr-ca/map-browser).
2. open the browser console.
3. refresh the page.
4. ensure the maps load their polygons correctly.
5. navigate to <<favorites>> using the link in the header.
6. navigate back to <<catalog>> using the link in the header.
7. see the error in the console.

```
DOMException: Node.removeChild: The node to be removed is not a child of this node
    React 84
    S scheduler.production.min.js:13
    I scheduler.production.min.js:14
react-dom.production.min.js:189:29
    React 13
    S scheduler.production.min.js:13
    I scheduler.production.min.js:14

```

**Comment by DamonU2** [comment]
New url - https://d2cv8c9ti3iyv0.cloudfront.net/fr-ca/map-browser

**Comment by jolevesq** [comment]
Not reproduceable
