### ISSUE TITLE
[REFACTOR] Refactor the existing Icon Stack after layers/icons in store has been implemented

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

We have implemented the Icon Stack component that is using fake data to display group of icons in layer list (screenshot below).

We need to refactor this component when the layers, and their icons are ready to be retrieved from the store.

Issue related to Icon Stack component: #1305 

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/7a458f61-9cc4-4abf-9593-d08721c2ca46)

**Comment by jolevesq** [comment]
Merged from another PR
