### ISSUE TITLE
[BUG] GeoChart should sync (or resets) the categories selected checkboxes when the inputs are reloaded

### ISSUE THREAD

**Issue by Alex-NRCan** [Canadian-Geospatial-Platform/geoview#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the moment, the GeoChart keeps the checked/unchecked categories when the inputs are reloaded. This leads to some desync between a fresh chart and what is actually being shown.

Have to decide if we keep a state or just refresh all to checked state on fresh loads.

**Comment by jolevesq** [comment]
We have an issue for this in Geochart: https://github.com/Canadian-Geospatial-Platform/geochart/issues/49

**Comment by Alex-NRCan** [comment]
Right, the issue in GeoChart is enough. This one here can be removed then.
