### ISSUE TITLE
Support OGC WMS in the details panel

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/GeoView#154]
Currently the details panel supports querying a WMS from an ESRI servers, add support for WMS from OGC

**Comment by jolevesq** [comment]
We now have API functions to gather getCapabilities. We it to validate info and remove the xmlToJson function as it is less efficient then wms-capabilities dependency

**Comment by jolevesq** [comment]
@yass0016 at the same time can we make sure there is no more Geo code in details panel

**Comment by yass0016** [comment]
Will be fixed with #296
