### ISSUE TITLE
[REFACTOR] TimeSlider Layout

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the moment, the time slider is using the field for title and we cant have custom elements.

### Expected Behavior

Time slider should be configurable for title, and description.

- For title default is layer name if no configuration provided
- Optional description text (only for configuration)
- Put field name/alias for the use field by time dimension

Update configuration schema at the same time

**Comment by DamonU2** [comment]
Duplicate of #1453?

**Comment by jolevesq** [comment]
@DamonU2 you are right, I modified the purpose of the issue
