### ISSUE TITLE
[BUG] Details panel will have to be able to work with undefined geometry

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is an issue in details tab left panel layers, in seems some layers have undefined geometry that causes issue when we click on layer name on left panel.

Please visit this page review the issue: https://canadian-geospatial-platform.github.io/geoview/public/package-time-slider.html

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/000d5af5-b4da-4d84-a6b3-5eb8c6edcc9a)

### Expected Behavior

We should handle the case when a selected layer has undefined geometry.

**Comment by jolevesq** [comment]
When there is no geometry, we should disable the select feature and zoom to feature capacity
