### ISSUE TITLE
[FEATURE] Have a tracking tool to help track which dependency has triggered a useCallback/useEffect

### ISSUE THREAD

**Issue by Alex-NRCan** [Canadian-Geospatial-Platform/geoview#1594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

As a developer, I'd like to have a dev tool that helps tracking which dependency has triggered a useCallback/useEffect hook.

Import [this package](https://github.com/simbathesailor/use-what-changed) (if possible/right react version) or code something home-made that heavily is inspired by that.

**Comment by jolevesq** [comment]
Fixed
