### ISSUE TITLE
Focus trap reverse shift

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#160]
On focus trap, reverse shift only cycle in the map and the skip element. Skip element should not be part of cycle at all. Chance ctrl-esc key to exit trap. Use another key combinaison.

**Comment by yass0016** [comment]
A tip maybe we could try removing the tabIndex attribute from those elements using jQuery or creating a function to select all elements in the leaflet map and remove their tabIndex
