### ISSUE TITLE
[BUG] Geochart useTranslation

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1632]
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.

**Current Behavior**
A concise description of what you're experiencing.

The Geochart package is using useTranslation but it is not available anymore

**Expected Behavior**
A concise description of what you expected to happen.

Use the getLocalizedMessage function from utilities like other packages. Now there is only one way to access i18n ressource.

**Steps To Reproduce**
1. Go to ...package-footer-panel-geochart.html
2. Open console and see the error

useTranslation is not a function
TypeError: useTranslation is not a function

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

**Comment by Alex-NRCan** [comment]
I believe this can be closed.
