### ISSUE TITLE
[BUG] In Details tab long text should wrap.

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/4933232/1c7c5608-30ff-44d6-9722-3bdc4aec2b09)

In details tab long text does not wrap, it gets cut (look at image above)

### Expected Behavior

Make the long text to wrap

**Comment by jolevesq** [comment]
This has been be solved as part of another PR
