### ISSUE TITLE
[BUG] Synch issue with loading features 'too late' vs rendering of plugins

### ISSUE THREAD

**Issue by Alex-NRCan** [Canadian-Geospatial-Platform/geoview#1669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes, when loading data-table or other plugins, the list of layers being displayed is missing some layers.
This happens randomly between fresh reloads, which seem to indicate a synchronization issue.

Can be tested with https://canadian-geospatial-platform.github.io/geoview/public/raw-feature-info.html and hitting F5 until it happens.

**Comment by jolevesq** [comment]
Fixed
