### ISSUE TITLE
[BUG] Changing Visibility of a layer results in an error

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/4933232/36a04763-484b-4d34-a9b5-52d40a4e7020)

Changing visibility of the the layer - 'Water quantity at monitoring stations'.
Click on the checkbox to toggling visibility on all items. You should see the error below.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/4933232/4d51d05b-0e5c-4ba7-97af-79161697ff35)

### Expected Behavior

There should be no error displayed when we toggling display of all items.

**Comment by jolevesq** [comment]
Solved by another PR
