### ISSUE TITLE
[BUG] The click event in some layers in left panel returns errors

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The order of layer data we receive from the state is not the same order as we display in UI, since are filtering them based on the visible layers in our "LayerList" component. 

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/1ba60854-f3b7-44b9-af2c-e1ba94101f69)

### Expected Behavior

We need to pass the correct index of the clicked layer to the event handle of the layer list in order to get the layer feature.

**Comment by Alex-NRCan** [comment]
This should be fixed now that PR #1739 has been merged. Can you try it again to confirm?

**Comment by amir-azma** [comment]
Yes all is working fine, tested in develop branch.
