### ISSUE TITLE
[FEATURE] Geolocator Filter

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user, I would like to be able to filter elements from the geolocator response

### Implementation UI

We should add the ability to filter from provinces or type of returned data like in RAMP

**Comment by kaminderpal** [comment]
Waiting for prod to release new version of API for geolocation data, will be available next week. Until then ticket is blocked.
