### ISSUE TITLE
[BUG] <Refresh Icon is not working in Layers footer panel>

### ISSUE THREAD

**Issue by kmansoor713** [Canadian-Geospatial-Platform/geoview#1700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user clicks on Refresh Icon in Layer Footer panel, it is not working.

### Expected Behavior

When user clicks on Refresh Icon in Layer Footer panel, The Layers detail should be refresh.

### Steps To Reproduce

1-Go to https://canadian-geospatial-platform.github.io/geoview/public/index.html
2-Check all the features are displaying on Footer panel
3-Click on Layers tab
4-Click on Refresh Icon in footer Panel

### Anything else?

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/a1dbc28a-fffd-41b2-82b3-f396a5851812)

**Comment by Alex-NRCan** [comment]
Took a look at this one, because I had some time, and indeed, all the button does is this:

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/94073946/e724de6f-b519-4c61-89e2-de248de0c9a0)

Still is a relevant issue.

**Comment by jolevesq** [comment]
Link to #1339
