### ISSUE TITLE
[BUG] olSource is sometime undefined

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1714]
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.

**Current Behavior**
A concise description of what you're experiencing.
We have pages who do not loads (map 2): https://canadian-geospatial-platform.github.io/geoview/public/use-cases.html
Because some olSource seems to be undefine when needed and the loaded does not trigger.

A temporary fix as been added to help debug in abstract-geoview-layers (addLoadendListener_TEMPORARY)

**Expected Behavior**
A concise description of what you expected to happen.
We should have synch functions to access ol layer to make sure they are ready

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/use-cases.html
2. See map 2

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

**Comment by Alex-NRCan** [comment]
To easily see why a map never gets 'ready' (which layer is taking the map hostage) set the GEOVIEW_LOG_LEVEL to 1 to activate detailed trace and the layer statuses will be shown everytime map readiness is checked.

**Comment by DamonU2** [comment]
Seems to have been resolved at some point
