### ISSUE TITLE
[FEATURE] Turn on/off details animation

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1732]
**Is there an existing issue for this?**
Please search to see if an issue already exists for this feature.
no

**Who request this Feature**
Individual, team, project, organization...
Hydro team

**User Story**
A concise description of what you expected to happen (one paragraph).
As a map creator, I would like to turn off details animation

**Implementation UI**
If needed, what user interface do you suggest, feel free to add mockups.
We should add an api function to turn on and off the details click animation
We should add a setting to configuration file to set it on and off automatically

**Additional context**

**Comment by cphelefu** [comment]
Which animation is this task referring to? All animations?
