### ISSUE TITLE
[BUG] Clicking on remove on multiple layers does not work

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you click to remove multiple layers from the "remove" tab in the layers panel, when timer finishes and the first layer is removed, it interrupts the removal of the other clicked layers

### Expected Behavior

All clicked layers should be removed once their respective timers elapse.

**Comment by cphelefu** [comment]
Investigated issue; this is how its happening;
When you a layer is deleted; the list of layers is modified - causing the LayersList component to re-render.
If any of the Layers is in the middle of a delete countdown - it is re-rendered causing delete to fail.
Not sure how to fix this one.
