### ISSUE TITLE
[BUG] User is not able to clearly find the specific feature selected while zoom

### ISSUE THREAD

**Issue by kmansoor713** [Canadian-Geospatial-Platform/geoview#1790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User is not able to clearly find the specific feature selected while zoom

### Expected Behavior

Show the click marker on zoom feature

### Steps To Reproduce

1-Go to https://canadian-geospatial-platform.github.io/geoview/public/index.html
2-Go to Basic details then Select any Feature in the map within Layers Tab
3-Go to Data Table tab and click on Zoom to feature Icon
4-User is not able to clearly find the specific feature selected while zoom

### Anything else?

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/72a8b912-4773-49c0-9321-d92fdda3371c)

**Comment by jolevesq** [comment]
We have the click marker appears on zoom
