### ISSUE TITLE
[FEATURE] Map accessibility

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

We need to make sure our accessibility features we have added in our project will work on screen readers and also with keyboard navigation

__Map__
- [ ] Map container focus
- [ ] Overview map
- [ ] Map information section (attribution, mouse coord, scale, rotation)
- [ ] Swiper

**Comment by amir-azma** [comment]
@kmansoor713  Can you please also check the accessibility features for the map for these features: 
- [ ] Map container focus
- [ ] Overview map
- [ ] Map information section (attribution, mouse coord, scale, rotation)
- [ ] Swiper

**Comment by kmansoor713** [comment]
1-	When user selects the Attribution and move the arrow key up-down, Hover over text “© His Majesty the King in Right of Canada, as represented by the Minister of Natural Resources” is also moving
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/48aed9b3-4363-4290-8f25-896e52888606)
 
2-	Arrow keys keep moving the map far Up-Down and Left-Right, It should stay within map boundry
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/b40080e5-09e4-4645-9c38-b2005bc763b3)
[Keyboard Navigation_Screen Reader #1791.docx](https://github.com/Canadian-Geospatial-Platform/geoview/files/14335363/Keyboard.Navigation_Screen.Reader.1791.docx)

**Comment by kmansoor713** [comment]
In 1822, All the issues are pretty much similar to 1791
1-	Keyboard Navigation pop up should display in middle of map
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/5f301b01-6dc4-41e5-9964-04d6a7726a4d)
2-	About Geoview __ Geo.Ca and Repo Link  are in similar color format, It should be different color.
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/25430b84-7ecc-400e-92dc-a36eef350b50)

**Comment by amir-azma** [comment]
Per our discussion in stand up today, the swiper accessibility feature looks fine for now. I pushed the fix for popover. 
the issue related to the link color in your last screenshot will be fixed in Chris PR as he worked on color themes.

**Comment by kmansoor713** [comment]
In #1822, All the issues are fixed except About Geoview - Geo.Ca and Repo Link are in similar color format, It should be different color. which will be fixed in Chris PR as he worked on color themes.
