### ISSUE TITLE
[FEATURE] FooterBar accessibilty

### ISSUE THREAD

**Issue by amir-azma** [Canadian-Geospatial-Platform/geoview#1794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

__FooterBar__
- [ ] Legend
- [ ] Layers
- [ ] Details
- [ ] Data table
- [ ] TimeSlider
- [ ] Geochart
- [ ] Guide

**Comment by amir-azma** [comment]
Tab navigation works fine according to https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/bc8db452-c26b-4b59-aa33-0300d00955b5)

Our tab panel works the same way as it works in MUI tab component page.

We should be able to navigate to tab elements using Left and Right keys only, not using the "Tab" key on the keyboard.
The "Tab" key on the keyboard should take us to the active tab, then we can use Left and Right arrows.

**Comment by jolevesq** [comment]
Cone from another PR
