### ISSUE TITLE
[BUG] No Features are displaying in map after Unhide the Eye Icon in Group and Individual Icon 

### ISSUE THREAD

**Issue by kmansoor713** [Canadian-Geospatial-Platform/geoview#1801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No Features are displaying in map after Unhide the Eye Icon in Group and Individual Icon 

### Expected Behavior

Unhide the Eye Icon in Group and Individual Icon should display the features in a map

### Steps To Reproduce

1-Go to https://canadian-geospatial-platform.github.io/geoview/public/index.html
2-Go to Basic details then Click on Layers Tab
3-Click the drop down of Point-Feature-group 
4-Unhide the Eye Icon in Point-Feature-group and Individual Icon

### Anything else?

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/5e77b7e6-1d60-4948-ac4c-822d6faf3126)

**Comment by cphelefu** [comment]
@jolevesq could not reproduce this error. Please confirm.

**Comment by jolevesq** [comment]
Could not reproduce
