### ISSUE TITLE
[API] Load Layer from API call with UUID Geocore

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

AS a web developper, I would like to load a layer from its key

### Implementation UI

We need to be able to load a uuid but we need to be able to pass geoview flag like removable

Layer removal flag should be apply at group and children level....
- group and children removable
- group removable only
- no removable

**Comment by Alex-NRCan** [comment]
Johann: reste à ajouter les options geoview a uuid sauve RCS... on peut dire que le 3/4 est fait à l'heure actuelle
