### ISSUE TITLE
[BUG] GeoView should work in React.StrictMode

### ISSUE THREAD

**Issue by Alex-NRCan** [Canadian-Geospatial-Platform/geoview#1810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to activate React.StrictMode for GeoView, it crashes. We should activate StrictMode at different levels to address all issues until we can activate it at the AppStart level in order to provide a more stable framework.

**Comment by cphelefu** [comment]
Looking at the errors when StrictMode is activated; it looks like that are all centralized. It might not be a lot of work to make this work.
