### ISSUE TITLE
[BUG] Layer not in Legend/Layers

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we load demo-osdp-biodiversity.html, the layer bisodiversity does not appear in legend even if loaded

{
              'geoviewLayerId': 'LYR1',
              'geoviewLayerName': { 'en': 'Canada\'s conserved areas' },
              'metadataAccessPath': {
                'en': 'https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/'
              },
              'geoviewLayerType': 'esriDynamic',
              'listOfLayerEntryConfig': [
                {
                  'layerId': '32'
                }
              ]
            },

### Expected Behavior

Layer should be in legend and layers panel

### Steps To Reproduce

1. Go to demo-osdp-biodiversity.html, demo-osdp-climate.html
2. Only one layer is in the panel

**Comment by DamonU2** [comment]
Layer 32 is null - the data has been moved (somewhere): https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/32
