### ISSUE TITLE
[BUG] Reporting UI Issues/Inconsistencies In Components

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We need to ensure our UI is consistency across all our components.
This issue is opened primary for logging issues noticed by developers.

**Comment by cphelefu** [comment]
The borders for layers are inconsistent... Both in details and data-table tabs
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/4933232/203ab1f7-e536-495a-8484-4f976a006e12)

**Comment by DamonU2** [comment]
Dark theme layers list has white on white:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/63123585/b5948cdb-013b-43fc-bee4-926c9c0a6c23)
