### ISSUE TITLE
[BUG] Add layers fails when adding 2 Geocore layers, says id already exists

### ISSUE THREAD

**Issue by Alex-NRCan** [Canadian-Geospatial-Platform/geoview#1832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

See also #793

### Current Behavior

When adding/removing and adding again a layer, with the add layers panel, there is an error saying the id already exists.

### Expected Behavior

We should be able to add/remove/add as we please

**Comment by jolevesq** [comment]
Solved as part of another PR on layer remove...
