### ISSUE TITLE
[FEATURE] Legend Update

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

AS a user who do not have access to layers panel, I want to see more thing and have some action on legend panel

### Implementation UI

We need to add basic function to legend panel

If a layer is not visible, instead of removing it from the legend, it should keep the box (no icon) in a kind of disable state.

We need some basic control over legend item like toggle visibility and highlight. it is a duplication of layers but this may be need for quick action on layers when legend is on the side.

On top of legend we should have expand/collapse all and turn on/turn on all visibility

**Comment by cphelefu** [comment]
This feels more like an extension of layers (just with a different UI). Is this for before release?
How would you like it done? I am thinking three dots at the end of every item in the legend with options that you are suggesting.
@jolevesq

**Comment by jolevesq** [comment]
Part of another PR
