### ISSUE TITLE
[BUG] Text hardcoded and not translated

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/4933232/86e373de-a387-4618-975b-570a9db27292)

The text highlighted in the image is not translated.

**Comment by amir-azma** [comment]
Thanks for letting me know, I will update the text with translation
