### ISSUE TITLE
[BUG] <Static Image not returning any table>

### ISSUE THREAD

**Issue by kaminderpal** [Canadian-Geospatial-Platform/geoview#1853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we click on Static Image layer in data table tab, it is returning empty array of features and in console is says 
`logger.ts:354 13:17:53.464 getAllFeatureInfo is not implemented! rror is thrown`

### Steps To Reproduce

1) Visit all layers page.
2) Select data table
3) Click on static image layer
4) Check the console for error.

**Comment by jolevesq** [comment]
Cannot reproduce
