### ISSUE TITLE
[BUG] Some geocore layers are not showing up in details

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the second map on https://canadian-geospatial-platform.github.io/geoview/public/geocore.html, all layers do not always appear in details. The details state layerDataArray is not properly populated. The map this is happening on has an (intentionally) faulty layerConfig that is not loaded in - this is the only difference from the first map, which is working as expected.

**Comment by jolevesq** [comment]
Fixed by PR to stabilize the layer-set and store propagation
