### ISSUE TITLE
[BUG] While in Full screen mode-Half of the Footer panel screen displayed as black screen 

### ISSUE THREAD

**Issue by kmansoor713** [Canadian-Geospatial-Platform/geoview#1887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While in Full screen mode-Half of the Footer panel screen displayed as black screen 

### Expected Behavior

While in Full screen mode-Half of the Footer panel screen should not display as black screen 

### Steps To Reproduce

1-Go to https://canadian-geospatial-platform.github.io/geoview/public/raw-feature-info.html
2-Go to Basic details tab 
3-Click on Full screen Icon on map
3-Scroll vertically up and down in Footer panel
4-Half of the Footer panel screen displayed as black screen

Replicated in Microsoft Edge & Google Chrome
v.0.1.0
2024-03-01

### Anything else?

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/feec4ded-7e8c-458b-8319-8578c939a2e3)

**Comment by cphelefu** [comment]
@kmansoor713 I couldnt reproduce this. 
What browser did you use? What are the dimensions?
