### ISSUE TITLE
The "Home" button may be misinterpreted by blind users

### ISSUE THREAD

**Issue by Malvoz** [Canadian-Geospatial-Platform/GeoView#192]
The button to reset to the initial starting point is named "Home":

![home-button](https://user-images.githubusercontent.com/26493779/114191197-72f2a180-994c-11eb-94cf-5260820f06d0.png)

It may be misinterpreted by blind users (specifically in the context of a web map) to mean the individual's home (perhaps indicative of obtaining the user's location through the Geolocation API).

We had this discussion for the `<mapml-viewer>` here: https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/200#pullrequestreview-525162807. In our case it was settled to be named "Reload" instead.

**Comment by jolevesq** [comment]
I will make it "Reset to initial view". I read the thread for mapML but I do not think reloads make sense. When we reload a map,  new call are made to server and some user setting like (layers state, added layers, ...) are lost. This is not the case when we set the extent. Plus the home icon seems misleading from a reset icon.

**Comment by Malvoz** [comment]
> I will make it "Reset to initial view". I read the thread for mapML but I do not think reloads make sense.

I personally agree with that. There's a context menu item (in Chrome at least) for iframes named "Reload" which reloads the entire browsing context of that particular iframe. Reloading is different than just resetting the view.
