### ISSUE TITLE
[BUG] Data table, detail Geopackages

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1922]
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
No

**Current Behavior**
A concise description of what you're experiencing.
Data table and details are nor working for geopackages.

**Expected Behavior**
A concise description of what you expected to happen.
It should work like any other vector file

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/geopackage.html, map 2-3
2. Click on Details and Data Table
3. See no layers in the list

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

**Comment by Alex-NRCan** [comment]
Possibly a duplicate/similar issue than #1855 ?

**Comment by jolevesq** [comment]
Related to #1999
