### ISSUE TITLE
[BUG] Group layers are taking the name of the first sub-layer

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#1923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Group layers are taking the name of the first layer in their listOfLayerEntryConfig, instead of the name assigned to them in the config.

### Expected Behavior

Group layers should take the name assigned to them in config, or the ID from the config if no name is used.

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/raw-feature-info.html
GeoJSON group layer is called "Polygons", and the point layer is called "Icons", when their names in the config are { 'en': 'GeoJSON Sample', 'fr': 'GeoJSON Échantillon' }, and { 'en': 'point-feature-group', 'fr': 'point-feature-group' }
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/63123585/37b0e4e4-d78c-405b-a6ed-4fb9622b6d0f)

**Comment by jolevesq** [comment]
Close as part of refactor layers PR
