### ISSUE TITLE
[CHANGE] Vector and Group layer bounds

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team, OSDP

### User Story

As a user I would like to see the bounds of my layer (the real bounds, not metadata). Some time layers has Canada as bounds but in realty, there is only few features in one province. For this reason, vector bounds should be calculate for features in the layer.

I think it is the way it is working right now, just need to make sure. For group of layer, it should merge all child extent and provide the overall.

**Comment by DamonU2** [comment]
This can be closed. Vector bounds are found through getBounds from abstract-geoview-vector, using source.getExtent() from OL. getExtent docs say: _Get the extent of the features currently in the source._

**Comment by jolevesq** [comment]
Will keep it open until OSDP is fine. I do not want to loose track
