### ISSUE TITLE
[FEATURE] OSDP Events

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

OSDP

### User Story

As a developer, I would like to be notified when user does action in the viewer. With this information I would like to rebuild a map with the actual state.

- [x] language change
- [x] basemap change
- [x] layers visibility
- [x] layers classification visibility
- [x] layer reorder
- [x] map zoom, pan
- [x] layers added (finish with status)
- [x] layers removed (completely)

- [x] layers panel status (layer path selected, layer: info, opacity, visibility, order, hover/click, swiper, ...)
- [x] legend status (collapse)
- [x] slider status
- [x] geochart status

### Implementation UI

We have events and state in viewer. Look what is a state and what is an event and provide access to it from the api. Look at how a page refresh can be trap and signal the viewer to take a snapshot of state to be reuse by developers.

We will need event to notify something happen and a function to export status of components

**Comment by jolevesq** [comment]
From OSDP

But in addition, on my front I followed up with Alex and can confirm:
1.	He believes he can trap any refresh including F5 and capture any required details before it takes effect
2.	Regardless, there are certain events that will require interaction to coordinate state details between the viewer and application in the moment that they are happening (e.g., requesting to add a layer, then waiting for an event confirming that it actually loaded so the record in the application can be locked)
 
My take-away from that is that there's an opportunity to streamline and simplify the complexity around managing viewer state information in the application.  So instead, we could structure the interaction around:
1.	Segregating refresh support actions: i.e., Eliminate the application need to trap actions whose purpose is only to preserve map state in support of refresh.  
a.	Rather, when any refresh is required, OSDP can call a geoView API to "pack up a suitcase" containing the geoView state information, refresh happens, and then OSDP passes back the same state information (in the same format) to the viewer thereby allowing it to reinstate itself.  
b.	This further decouples geoView and OSDP synchronizaiton complexity, because geoView controls both the package input and output format as it evolves – without the application needing to “understand” the package details or keep pace with it.
2.	Zero-focus API/Event Combo support to Business needs: geoView APIs are exposed in support of just the services where the application needs to request a specific action (e.g., add this layer), and the accompanying partner events that complete the end-to-end coordination.
3.	Exposing events resulting from viewer-side actions that affect the application. e.g., Inform the application when a layer is deleted, allowing it to now be unlocked and disassociated from the map in the application.

**Comment by gfouquetasselin** [comment]
@jolevesq I need to provide an update to OSDP Team tomorrow during the Team Lead meeting on Status and critical path for Geoview, for both OSDP events and Functions/API and layer support. Is there a JIRA ticket for all tose three items. 
What's the remaining tasks to be done so CMSS team can start their work in terms of like-to like Checlkist (see attach diagram built by Darin)?
<img width="760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2dYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5926a26d5d95d7d197ed2e492168e0097e0c9339/image.png" alt="image.png" />
