### ISSUE TITLE
[BUG] Payload does not contain full geojson

### ISSUE THREAD

**Issue by namangera** [Canadian-Geospatial-Platform/geoview#1934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

  // Listen for layer added
  cgpv.api.event.once(
    cgpv.api.eventNames.LAYER.EVENT_LAYER_ADDED,
    (payload: never) => {
      console.log(payload)
      loader.style.visibility = 'hidden'
    },
    `${mapId}/${layerID}`

the payload does not have the geojson when using addGeoviewLayer for a GeoJSON geoviewLayerType

### Expected Behavior

the payload should have the geojson

### Steps To Reproduce

add a geojson layer using cgpv.api.maps[mapId].layer.addGeoviewLayer
call the payload

### Anything else?

I want to be able to access the geojson for each layer because I use it to send other information such as runtime and statistics for pygeoapi process.

**Comment by jolevesq** [comment]
Merged as part of #2323. IT will not return the geoJSON properly but the layer itself who can then be query to get all features
