### ISSUE TITLE
[BUG] Data table does not have data for a layer

### ISSUE THREAD

**Issue by namangera** [Canadian-Geospatial-Platform/geoview#1935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I call a pygeoapi process, the layer shows up in the layers panel and I can access the data table within the layers panel but the data table in the footer does not work.

### Expected Behavior

load data in the table

### Steps To Reproduce

On the NRCan network, using this link https://app.chn-rhc.geogc.ca/
Run a downstream process and click on the data table in the footer, the downstream layer is not there.
Using react components you can see that the data is loaded but does not show up in the layer.

**Comment by jolevesq** [comment]
@namangera This is a know bug, the layer is on the map but you need to show/hide from layers panel to make it appear in details and table. We will look at this
