### ISSUE TITLE
[BUG] GeoCore UUID Layer is not loading, Shows spinning wheel

### ISSUE THREAD

**Issue by kmansoor713** [Canadian-Geospatial-Platform/geoview#1956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hillshade map of the Digital Surface Model layer is not loading under Legend tab

0fe65119-e96e-4a57-8bfe-9d9245fba06b

### Expected Behavior

Layer should be loaded

### Steps To Reproduce

1- Go to https://canadian-geospatial-platform.github.io/geoview/public/index.html
2- Click on Basic Add Layers tab_Scroll down to GeoCore UUID Layer
3- In the Add Layer drop down_select "0fe65119-e96e-4a57-8bfe-9d9245fba06b" to add the layer

### Anything else?

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/151664178/1983fe34-48e7-4a21-a36c-f7cf99268982)

**Comment by jolevesq** [comment]
This has been fixed by another PR
