### ISSUE TITLE
[BUG]  esriDynamic wrong layerDef

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1996]
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.

**Current Behavior**
A concise description of what you're experiencing.
 When we load this layer below, there is an error with getFeatureinfo...
```
'listOfGeoviewLayerConfig': [{
      'geoviewLayerId': 'wmsLYR1',
      'geoviewLayerName': {
        'en': 'earthquakes',
        'fr': 'earthquakes'
      },
      'metadataAccessPath': {
        'en': 'https://gisp.dfo-mpo.gc.ca/arcgis/rest/services/FGP/KDE_Analyses_Coral_Sponge_2016_EN/MapServer',
        'fr': 'https://gisp.dfo-mpo.gc.ca/arcgis/rest/services/FGP/KDE_Analyses_Coral_Sponge_2016_EN/MapServer/'
      },
      'geoviewLayerType': 'esriDynamic',
      'listOfLayerEntryConfig': [
        {
          'layerId': '0'
        }
      ]
    }]
  },
```
**Expected Behavior**
A concise description of what you expected to happen.
get feature info should work

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/sandbox.html
2. Click on Add config snippet and create the map
3. Move pointer on the map

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

**Comment by DamonU2** [comment]
Error is no longer appearing.
