### ISSUE TITLE
API dialog box

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#200]
Create a dialog component from the api to be reusable from outside. Just pass content and callback

**Comment by jolevesq** [comment]
Related to #250

**Comment by yass0016** [comment]
@codey-codes 

[] an api to create a modal, provide an id or generate one if not provided
[] an api to delete a modal using the id
[] ability to see all created modals on the map
[] an api to open/close the modal
[] an api to add action buttons to the modal's header or footer
[] an api to change the body content of the modal
