### ISSUE TITLE
[BUG] CSS bug -- GeoView objects hiding web page header

### ISSUE THREAD

**Issue by G-Boyce** [Canadian-Geospatial-Platform/geoview#2052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When scrolling the map downwards, a couple of objects on the map (fill in the correct name for the GeoView tools here) when moving upwards, hide the header of the web page.

I believe this is a problem in the GeoView CSS.  But not sure, could be malformed CSS in Data Management Plan (DMP) web page.

Before scrolling down, I see:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/168113972/e135218a-44b3-4511-b2d5-39c4e991766b)

After scrolling down, note where the GeoView objects hide the web page header:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/168113972/47ac670e-edaf-4374-98d5-21f38773dacf)

Possible solution:  I can turn off a GeoView CSS element (z-index) and the GeoView objects hide when scrolling.  (Definition:  "The z-index CSS property sets the z-order of a positioned element and its descendants or flex and grid items. Overlapping elements with a larger z-index cover those with a smaller one.")

In Firefox, when I Inspect the code, I can turn off (uncheck) z-index in:
- Left panel:  css-bd62fd (z-index value= 1100)
- Right panel:  css-6oq0bd (z-index value= 150)

Beforehand, with z-index still checked, in Firefox Inspector :
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/168113972/87740e33-ec58-47e4-a3ec-1b1334c6ef24)

Afterwards, with with z-index unchecked for Left-hand panel -- panel no longer hides header:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/168113972/7030a3d8-16c5-42e5-b6a2-e617e3234d4f)

In Firefox Inspector, it says its an "Inline" CSS element, and its Path is:

> html body.function-list div.r-vbar-page div.r-content-col div.r-body div.r-top div#form_top_1.r-form div.row div.r-ori-vert.col-md-12 span div#mapOne.geoview-map div.MuiBox-root.css-1418lhx div#shell-mapOne.geoview-shell.MuiBox-root.css-1hz9ysc div#map-mapOne.mapContainer.MuiBox-root.css-j2itcf div.interaction-dynamic.MuiBox-root.css-bd62fd

### Expected Behavior

If I turn off (uncheck) both z-index elements above, I see, correctly:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/168113972/bdc018d9-4b45-413d-961f-64041f509e86)

### Steps To Reproduce

On a test web page of the DMP tool, I've added GeoView.

You don't have access to these pages (you'd need a login).  So, if you'd like me to Save the HTML, I could do that.

### Anything else?

It's been more than a decade since I worked with CSS, so this is my inexpert opinion about the problem.

**Comment by jolevesq** [comment]
@G-Boyce Quick questions, do you really want to scroll the map under your set of tools? Would you prefer to have your tool and your map position in the same div one after the other so when you scroll they are in synch? Do you have a url for us to test?

**Comment by G-Boyce** [comment]
I no longer see this problem, so you must have changed something that fixed it.  (Even though the z-index remains 1100)
So, unless the problem re-appears, nothing more needs to be done.

The header on the page stays visible when you scroll down.  So, yes the header should remain visible, and the map and tools should hide when you scroll down.

The URL is [https://nrqcg1kwvasp002.nrn.nrcan.gc.ca/dev/geo_dmp/project_summary_list.php](https://nrqcg1kwvasp002.nrn.nrcan.gc.ca/dev/geo_dmp/project_summary_list.php)

Would you still like to see the site to test?  (I'd need to get you a guest login.)

**Comment by G-Boyce** [comment]
@jolevesq

For future use:  on the login page (to the above link), there's now a "login as guest" link.

**Comment by jolevesq** [comment]
Thanks! I saw the implementation @G-Boyce, It is very nice. From a quick look I see we have collision with font-size as text is smaller in your site.

**Comment by jolevesq** [comment]
Problem no longer there
