### ISSUE TITLE
[REFACTOR] Legend - Export AppBar

### ISSUE THREAD

**Issue by kaminderpal** [Canadian-Geospatial-Platform/geoview#2066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we open export modal from appbar and there is no footerbar and legend is in appbar. 
Export modal template show legend container from appbar legend. which is not correct bahavior.
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/7388956/e463bf3c-cb38-466a-a0d7-a7449c4c0f0f)

### Expected Behavior

In export template modal, legend will always need to show from footer bar instead of appbar, if no footerbar, then legends needs to be hidden in export modal template.

### Steps To Reproduce

1) Visit page which have app bar http://localhost:8080/raw-app-bar.html
2) Click on legend icon and click on export button.
3) Vertical legends will be displayed.

**Comment by jaredkinger** [comment]
A broken image is currently being shown for the legend in the export modal when the legend is only in the App Bar.

1. Go here: https://dev.geo.ca/geoview-test/export-legend.html
2. Export the map
3. View the broken image in the modal where the legend should be
