### ISSUE TITLE
[BUG] default styles not in icons

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#2072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Layers with default styling provided by geoview do not have icons in footer panel.

### Expected Behavior

Icons should be generated for default styles

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/raw-add-layers.html
Add https://canadian-geospatial-platform.github.io/geoview/public/datasets/geojson/points.json
Check legend

**Comment by cphelefu** [comment]
Not sure what is the issue here. @DamonU2 can you please add more details.
