### ISSUE TITLE
[BUG] Viewer applies styles to the <body> tag

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geoview#2107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The viewer injects CSS that is applied to the body causing typography and background changes to the entire page the viewer is being displayed on.

The styles being applied:

```
body {
    margin: 0px;
    color: rgb(66, 66, 66);
    font-family: Roboto, Helvetica, Arial, sans-serif;
    font-weight: 400;
    font-size: 1rem;
    line-height: 1.5;
    background-color: rgb(248, 248, 250);
}
```

### Expected Behavior

This styling should only be applied to the viewer and not the entire page.

### Steps To Reproduce

1. Go to https://wordpress.dev.geo.ca/wp-content/geoview/examples/body-styles.html (must be on NRCan network)
2. Watch the background change from lightblue to rgb(248, 248, 250) and the heading font change from Georgia to Roboto upon initializing the viewer

**Comment by jolevesq** [comment]
@jaredkinger that is weird, we do not inject directly css from what I know and see. We will need to dig to see what is going on.

**Comment by jaredkinger** [comment]
@jolevesq I was able to track down where these styles are being imported from. They are being imported from `<CssBaseline />` in [app-start.tsx](https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/core/app-start.tsx#L106)

CssBaseline adds some styles to the `<html>` tag as well. To maintain these base styles without affecting the rest of the page CssBaseline could be swapped out for ScopedCssBaseline instead. That will wrap the .MuiBox-root div in a .MuiScopedCssBaseline-root div and apply the base styles to it allowing all children to inherit the base styles.

Example:

```
return (
    <StyledEngineProvider injectFirst>
      <ThemeProvider theme={cgpvTheme}>
        <ScopedCssBaseline>
          <Suspense fallback="">{getInlineMaps()}</Suspense>
        </ScopedCssBaseline>
      </ThemeProvider>
    </StyledEngineProvider>
);
```
