### ISSUE TITLE
[BUG] Invalid GeoView layerType (GeoJSON) error message

### ISSUE THREAD

**Issue by G-Boyce** [Canadian-Geospatial-Platform/geoview#2176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When loading the [GeoJSON Layers demo page](https://canadian-geospatial-platform.github.io/geoview/public/geojson.html#HLYR1), an error message is seen in the browser Console page:  
- "Invalid GeoView layerType (GeoJSON)."

Map appears to load correctly, but haven't tested to see if this is affecting other aspects of the map (tools, etc).

### Expected Behavior

Almost 100% sure this message wasn't there before.  But don't know when it appeared -- maybe in last 2-3 weeks?

### Steps To Reproduce

1. In Firefox v126 browser
2. Didn't change default map config
3. Load [GeoJSON Layers](https://canadian-geospatial-platform.github.io/geoview/public/geojson.html#HLYR1) demo page
4. Browser Console shows following output:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/168113972/0f08ea1a-0a3a-4d28-bf0a-b5aeb826f6ae)

**Comment by jolevesq** [comment]
Done as part of another PR
