### ISSUE TITLE
[BUG] Group Added to Details/Table

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#2194]
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
No

**Current Behavior**
A concise description of what you're experiencing.
When we add airborne geocore layer, a group is added to layer set

OR It is missing one of the layer in the group

**Expected Behavior**
A concise description of what you expected to happen.
No group in layerset, especially details, table, slider, chart....

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/geocore.html
2. Click on details, data table
3. See loading item

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb13d657cedb89e79c50d336f3a6c0c755035a5f/image.png" alt="image.png" />

![Uploading image.png…]()

**Comment by Alex-NRCan** [comment]
Additional information: It seems the identify query on the layerid 2 isn't working on the server-side:

HTML:
https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/airborne_radioactivity_en/MapServer/identify?geometry=-75.69%2C45.32&geometryType=esriGeometryPoint&sr=4326&layers=&layerDefs=&time=&layerTimeOptions=&tolerance=7&mapExtent=-75.95992726354629%2C45.13839484043886%2C-75.34516685881795%2C45.520728538964406&imageDisplay=1019%2C800%2C96&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&dynamicLayers=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnUnformattedValues=false&returnFieldName=false&datumTransformations=&layerParameterValues=&mapRangeValues=&layerRangeValues=&clipping=&spatialFilter=&f=html

JSON:
https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/airborne_radioactivity_en/MapServer/identify?f=json&tolerance=7&mapExtent=-75.95992726354629,45.13839484043886,-75.34516685881795,45.520728538964406&sr=4326&imageDisplay=1019,800,96&geometryType=esriGeometryPoint&geometry=-75.68974758672083,45.319599571994296&returnFieldName=true

**Comment by jolevesq** [comment]
Seems to work now...
