### ISSUE TITLE
[BUG] ESRI Features limited by MaxRecordCount

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geoview#2199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ESRI Feature layers that have a MaxRecordCount that is less than the total number of features are failing to display all of the features on the map. The MaxRecordCount is also affecting the number of features being fetched for the data table in both esriFeature and esriDynamic layers.

### Expected Behavior

All features should be fetched by looping when the MaxRecordCount is less than the total number of records.

### Steps To Reproduce

1. Go here: https://wordpress.dev.geo.ca/wp-content/geoview/examples/max-record-count.html
2. The Advance Polling District Boundaries of 2019 layer is not displaying all the features on the map. RAMP version is [here](https://geo.ca/wp-content/Viewer/config-int-ADMINISTRATION-iframe-map-en.html) for comparison. 
3. View the data table and load the features the layer. The features only load 1000 entries instead of 6172 entries
4. Toggle the visibility of the Completed layer and view it's data table. The features only load 1000 entries instead of 3094 entries

### Anything else?

Config from the example: [max-record-count.json](https://github.com/user-attachments/files/15538989/max-record-count.json)

**Comment by DamonU2** [comment]
Changes not applied to ESRI Dynamic for data table
