### ISSUE TITLE
[BUG] Time slider right anchor won't be respected when using the "Forward" button

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the ["Package time slider" config](https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json)

In the "Time Slider" tab, use the first layer of the list: "Historical Flood Events". Move the right anchor towards the right just a bit. eg. past the "1779-01-01" tick mark: 

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/40869362-c60f-40f0-8c6c-f081c2496b00)

Then use the "Forward" button:

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/f83f8ede-f938-4f15-a621-f8700917a9e3)

It brings back the right anchor to its original position. It seems the initial preset range overwrites the one manually set:

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/973922a9-7ee1-4ca9-9194-d5c2b6455077)

If you click once again on the "Forward" button, the range will move towards like expected but using the default preset range:

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/d4e85b20-be8e-44d0-b502-50e14057a1d7)

Where ever you position any of the anchors and use the "Forward" or "Back" buttons on this layer, the preset range will systematically overwrite the range you set.

### Expected Behavior

Range you manually set should be respected when using the "Forward" and "Back" buttons.

**Comment by DamonU2** [comment]
It's not a preset, there is a maximum size for the steps of 20% of the range, and if the manually set range exceeds it, it will be reduced.
