### ISSUE TITLE
[FEATURE] Chart - Add a "Logarithmic / Static scale" option at the top

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2247]
It's a common pratice for radiological data to be charted using a logarithmic scale.  Since the Radiation Protection Bureau of Health Canada is our main - and only - client using the chart plugin wihitin our viewer, adding the option in a drop-down menu on top of the chart, like the "Steps" representation would be a great enhancement.

HC did request this in the past and it is on their wish-list.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/36638951-83a1-42e6-9147-d2ba53a4d77c)

**Comment by jolevesq** [comment]
Plus the doenload button font is no in synch with other button font
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/3472990/0e407597-4aab-4dd8-acea-4314c1b5807f)

**Comment by jolevesq** [comment]
Merged
