### ISSUE TITLE
Refactoring cluster marker styles

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/geoview#225]
Incorporate the css into the viewer itself as component or sub component in assets/style/theme.tsx. Also move repetitive code in constants.

**Comment by jolevesq** [comment]
@ychoquet Is still good or we close?

**Comment by jolevesq** [comment]
@ychoquet Is this done by the merge or more work need to be sone?

**Comment by ychoquet** [comment]
Needs more work.

**Comment by jolevesq** [comment]
Open Layers support cluster, see exemple and implement a simple version. If complex version needs to be created, we should do it as a package (even may external) as core package should try to avoid dealing with OL directly.

**Comment by jolevesq** [comment]
Close this issue, will be deal by #536
