### ISSUE TITLE
[FEATURE] Method to handle feature info for outlier layers

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#2259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

We need the ability to add/correct alias fields for layers that do not provide metadata, do not build the aliases into the features, and have inconsistent feature data (ex. ea4c0bdb-a63f-49a4-b14a-09c1560aad0b). This layer lacks the first two, and different features, even in the same category, return different numbers of features, so the implemented method of handling this does not work.
Previously handled with:
https://osdp-psdo.canada.ca/dp/assets/osdp/templates/wms-bc-script.js

https://maps.canada.ca/wmsproxy/ws/wmsproxy/executeFromProxy?https://openmaps.gov.bc.ca/geo/pub/WHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT/ows?CRS=EPSG%3A3978&I=460&J=456&STYLES=&FORMAT=image%2Fpng&BBOX=-5654057.176149353%2C-1454941.5086360178%2C3362960.8578867167%2C4069569.540386081&SERVICE=WMS&REQUEST=GetFeatureInfo&VERSION=1.3.0&WIDTH=1136&HEIGHT=696&QUERY_LAYERS=pub%3AWHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT&LAYERS=pub%3AWHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT&INFO_FORMAT=text%2Fhtml

**Comment by jolevesq** [comment]
To solve this, we need to store the featureinfo inside geocore so when we create the geoview config from geocore, we do not take  only what is stored for rcs but we take what is store for layer config inside gcs
