### ISSUE TITLE
[FEATURE] Improvements to demo page

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#2279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

The current demo could be improved to look a little nicer.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/4933232/d4bf9b17-61b8-4051-981e-6a4cff96998e)

### Implementation UI

1. Add more controls to our config panel.
2. Panel appears of top or left depending on screen size.
3. Config panel can also ne collapsed.
4. User can toggle between map & code/json.
5. Produced JSON always matches the config settings.
6. All configs are passed in the URL (encoded) thus users can shares settings by copying the link.

**Comment by jolevesq** [comment]
A new repo called geoview-demo has been created
