### ISSUE TITLE
OSDP List of URL - highly integrated

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#2294]
**Highly-integrated datasets (~40) that are baked into Static web pages and search events**

**They should be all integrated in the OSDP demo pages**

**DEMOS PAGES**
- [x] Learn_AIR - 881a606b-69e0-473f-841d-aec9e2815e58
- [x] Learn_AIR	- f6660f68-5e78-47b3-9306-9805e1d3d6e9

- [x] Learn_WATER - b6b6d5a6-bded-4b6e-9e8a-17f6e1b538dc
- [x] Learn_WATER - 94a51051-ad11-499a-b5f1-8c97b29f695c

- [x] Learn_CLIMATE	- 4221c508-00c9-4011-aca6-b0a017fc90dc
- [ ] Learn_CLIMATE	- 3e9cc0c9-7e59-478b-befb-a584674baa75

- [x] Learn_BIODIVERSITY - 6c343726-1e92-451a-876a-76e17d398a1c
- [x] Learn_BIODIVERSITY - 91219d24-e877-4c8a-8bd2-b2b662e573e0

- [x] Learn_LAND - 0a309f2c-4f11-4ddb-bce1-e7ba6f8c20cf
- [x] Learn_LAND - 4e615eae-b90c-420b-adee-2ca35896caf6
- [x] Learn_LAND - c688b87f-e85f-4842-b0e1-a8f79ebf1133

- [x] Learn_SOCIETY	- 0a309f2c-4f11-4ddb-bce1-e7ba6f8c20cf
- [x] Learn_SOCIETY	- 44cebdbe-a3a5-4f02-9f1d-66af8dbf76f1
- [x] Learn_SOCIETY	- 66909604-f685-4f1b-a3d8-447996e6b41b

- [x] Learn_ECONOMY - f5f2db55-31e4-42fb-8c73-23e1c44de9b2
- [x] Learn_ECONOMY - 65d3db23-b83c-4f49-ab93-65c59ee0e6aa

- [x] Learn_HEALTH	- d256b422-2834-40a2-9f0c-bd5fc32781b2
- [x] Learn_HEALTH	- 21b821cf-0f1c-40ee-8925-eab12d357668

** OTHER UUID**

- [x] MapArea_Project_IAAC - f4c51eaa-a6ca-48b9-a1fc-b0651da20509
- [x] MapArea_Project_DFO - a57d5eef-e482-4c05-bcd5-56a0f15b9f02
- [x] MapArea_Project_BC - ea4c0bdb-a63f-49a4-b14a-09c1560aad0b
- [x] MapArea_Project_TC - 3af377be-801d-4ebf-9137-869b3080bfa5
- [x] MapArea_Project_CER - 039fbd92-43c2-4805-b210-d65703712e37
- [x] MapArea_Project_CNSC - 6478153c-829f-4649-bd52-41f63b41021f
- [x] MapArea_Monitor_Air - e6cc3ae2-92b1-4df6-87ff-698a1cd5a7bd
- [x] MapArea_Monitor_Water - b6b6d5a6-bded-4b6e-9e8a-17f6e1b538dc

- [x] Dev_Energy	1	039fbd92-43c2-4805-b210-d65703712e37
- [x] Dev_Energy	2	40fbe40c-01cd-49d3-8add-0d20ed64c90d
- [x] Dev_Energy	3	0e76433c-7aeb-46dc-a019-11db10ee28dd

- [x] Dev_Forestry	1	9d00aa0a-a825-4804-b29b-1eff4f82a085
- [x] Dev_Forestry	2	d576e878-04f1-4c4f-8428-e16c371e9a3c
- [x] Dev_Forestry	3	ee1580ab-a23d-4f86-a09b-79763677eb47

- [x] Dev_Mining	1	488faf70-b50b-4749-ac1c-a1fd44e06f11
- [x] Dev_Mining	2	22b2db8a-dc12-47f2-9737-99d3da921751
- [x] Dev_Mining	3	000183ed-8864-42f0-ae43-c4313a860720

- [x] Dev_Fisheries	1	e0fabad5-9379-4077-87b9-5705f28c490b
- [ ] Dev_Fisheries	2	a57d5eef-e482-4c05-bcd5-56a0f15b9f02
- [x] Dev_Fisheries	3	db177a8c-5d7d-49eb-8290-31e6a45d786c

- [x] Dev_Transportation	1	e218c8cb-5039-4706-b58f-d54c6c11a6fc
- [x] Dev_Transportation	2	c5c249c4-dea6-40a6-8fae-188a42030908
- [x] Dev_Transportation	3	3af377be-801d-4ebf-9137-869b3080bfa5

- [ ] Dev_Agriculture	1	d765cc41-8ee0-4aca-be4b-084448e52a58
- [ ] Dev_Agriculture	2	199e4ab6-832b-4434-ac39-e4887d7cc4e5

**Comment by jolevesq** [comment]
Works for me but took a lot of time and when on the page, it freeze the tab if I switch page then return

- Learn_BIODIVERSITY - 6c343726-1e92-451a-876a-76e17d398a1c loads but display nothing

This query took a while to return the image
https://maps-cartes.ec.gc.ca/arcgis/rest/services/CWS_SCF/CPCAD/MapServer/export?F=image&FORMAT=PNG32&TRANSPARENT=true&LAYERS=show%3A0&layerDefs=%7B%220%22%3A%20%22(BIOME%20%3D%20%27T%27%20and%20PA_OECM_DF%20in%20(1%2C%203%2C%202%2C%204%2C%205)%20or%20BIOME%20%3D%20%27M%27%20and%20PA_OECM_DF%20in%20(1%2C%203%2C%202%2C%205))%22%7D&SIZE=1570%2C1200&BBOX=-16743429.248986572%2C6858159.4413429415%2C-10576246.226071198%2C11571929.904717747&BBOXSR=3857&IMAGESR=3857&DPI=90

**Comment by ychoquet** [comment]
Yes, you're right. However, we cannot be faster thant the service response time.
