### ISSUE TITLE
[BUG] In Default configuration - Details tab not showing guide first (shows un-ending skeleton)

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#2313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Default configurations - details tab is showing an un-ending animation instead of the guide tab.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/4933232/0aa12f4b-b9d1-4153-bd1c-c3e01107eae4)

Map 4
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/3472990/1187b0b0-d40c-401b-81b2-854a95fe8e0c)

### Expected Behavior

When clicking details tab (in default configuration it should start with guide).

**Comment by jolevesq** [comment]
This is happening when layer list is empty
