### ISSUE TITLE
Creating monorepo structure

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#233]
Going monorepo.... will try Lerna and may modify in the future

**Comment by yass0016** [comment]
- Make geoview-core build and run from rush
- Make geoview-details-panel work
    - allow it to build (currently because we are were importing functions, types, interfaces directly from the core this doesn't work)
    - allow the ability to access API calls from the geoview-core that don't depend on the mapInstance
        - types
        - event names
        - etc...
    - allow the ability to load API calls that depend on mapInstance 
      *(mapInstance will be passed to the plugin when loading the plugin for that map)
    - should we have material ui installed on the plugin or should we find a way to export it from the core?
        - suggestion: move any (ui) out of the geoview-core. 
            Remove any reference to material ui from the core to make it lighter
- Move a component outside of geoview-core and make geoview-core lazy load it (code splitting)
- Create a way to move allow compiled JS files for plugins, components to one location to load them with the core

**Comment by jolevesq** [comment]
@yass0016 For the build, Rush let you import from one packages to another at build/serve time. Should it solve the types and function imports?

For passing the map instance, you are right, at run time the viewer will know from the div configuration what plugins to call and pass the map instance to the plugin init function.

For Material, we have core component who are using it. We cn import only what is needed or create another packages with all Material raw component and import only that component inside the core and customize it. Se we end up with

- GeoView-Core
- GeoView-Geo
- GeoView-UI
- Geoview-Comp-DetailPanel
- GeoView-Comp-NorthArrow
- ...

**Comment by vijendtra** [comment]
@yass0016 wrt to plugin, yes MUI will be install at plugin level  ,it would not need any reference or object  form core wrt to MUI  or any other library ,think this in a way like a small microservice (though it's not ) into a application which will handle all the  API call or any dependency separately.

**Comment by jolevesq** [comment]
For UI creating component from other UI pat will stay in UI (panel is compose of Card, CardHeader, ...). 

For Other UI like notistack, it should go to UI. UI will keep the UI (basic logic like WCAG and setContent, getContent, set/getState, ...) and component logic will go to component inside the core. Need a clear separation between UI and core same as between Geo and Core. So we can develop reusable Geo and UI without interfering with component.

There will be no import of Material-UI or Third library UI inside core

Component will reuse UI from UI folder so if we upgrade something it will cascade to all the child.
