### ISSUE TITLE
Create function to add vector to a map

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#24]
We need the ability to add 
- [x] Polylines
- [x] Points (circle)
- [x] Polygons

Those geometries may be added in different projections ([projection issues](https://github.com/Canadian-Geospatial-Platform/GeoView/issues/25))
Those geometries needs to be added as [layer group](https://leafletjs.com/reference-1.7.1.html#layergroup) or [feature group](https://leafletjs.com/reference-1.7.1.html#featuregroup)

The functions needs to be part of the api so we can create from inside the viewer and also from the outside.

On the sample page, create a button with a text box where we can add geometry coordinates to add vector on the map

**Comment by yass0016** [comment]
Do we need to add the vectors manually by passing lag/lng coordinates or using the mouse to draw the vectors? If we will be using the mouse to draw the vectors, can we use the leaflet.draw module to handle it or should we create our own?

**Comment by jolevesq** [comment]
Yes, this one is more a function to add geometry to the map, e.g. a layer boundary box. A function call the api with the coordinates to add the polygon to the map. The draw with a mouse is something else. Look at https://jolevesq.github.io/contributed-plugins/draw/samples/draw-index.html. At this point we may want to use the leaflet draw module (#52).
