### ISSUE TITLE
Support OGC PyGeoApi

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#241]
PyGeoAPI: https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#data-access-examples

Create PyGeoAPI object to handle request to help show feature on maps and filter. PyGeoApi may act as a layer-collection type.

Sample site:
- https://sq3ynzmc86.execute-api.us-east-1.amazonaws.com/dev/collections/lakes/items/0
- https://b6ryuvakk5.execute-api.us-east-1.amazonaws.com/dev/collections/canadian-geospatial-platform

**Comment by LarryWang888** [comment]
The PyGeoAPI services include OGC API - Features, OGC API - Coverages, OGC API - Tiles , etc. These services will be added as geoview layers in individual tickets.  OGC API - Features will be addressed in #210, OGC API - Coverages will be added in #194, etc. This issue can be closed for now.

**Comment by LarryWang888** [comment]
Will add another two issues for Coverages, OGC API - Tiles support and OGC API - Coverages support

**Comment by jolevesq** [comment]
Done with refactor
