### ISSUE TITLE
[FEATURE] Demo page to generate custom config

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

Build a demo page to generate custom configs using createMapConfigFromMapState.

### Implementation UI

- basic map with legend and layers in the footer - with layers panel open on load
- buttons/checkboxes to add/remove components from app bar and footer bar
- button/checkbox to add/remove footer bar
- toggle/button to switch between english/french
- button to call createMapConfigFromMapState and put config in text box under the map

**Comment by jolevesq** [comment]
This will be done by our new repo https://github.com/Canadian-Geospatial-Platform/geoview-demo, https://canadian-geospatial-platform.github.io/geoview-demo/
