### ISSUE TITLE
[BUG] Layer loading order

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#2491]
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
No

**Current Behavior**
A concise description of what you're experiencing.
When we load multiple layers one after the other, order is not respected

JIRA: https://fgp-pgf.atlassian.net/jira/software/projects/OSDP/issues/OSDP-1811

The Search Event Master defines how the search and map areas are modified for each search request.  For example, in the Learn_LAND event below, 3 layers are added in an order requested by OCS, resulting in a clean consistent view for everyone with the most important layers toward the top.

If I open a browser session and initiate the following, the application does indeed request for the 3 layers to be added.  However, they do not appear in the correct order in the Legend or the Layers tabs.  To reproduce:

Open a new browser tab and open OSDP GREEN DEV: https://green.dev.osdp.aws.nrcan-rncan.cloud/en

Visit the Learn About Land page: https://green.dev.osdp.aws.nrcan-rncan.cloud/en/learn-about/land

Click the Search for Land Content button at the bottom of the page under the map.  This will initiate the Learn_LAND Search event that will pre-populate the viewer with 3 layers, in which the 2010 land layer is hidden while the other 2 are marked as visible.

Note the difference between the sequence above and the result in geoView.  

The first 2 layers on the Layers tab are out of order as compared to the expected order

The order represented on the Legend tab is different again, and still not a match for the requested order.

Clicking on hide/show of the legend in in the Legend tab resulted in the order being rejuggled as I watched, but again not to the originally requested order

Following the above sequence of events in a browser tab that has first run through other cases may actually present the layers in the correct order on the Layers tab.  However, every time I run through the above steps as the first test case in a new browser, it always presents the same issue noted above. 
**Expected Behavior**
A concise description of what you expected to happen.

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
2. In the console, use the     cgpv.api.maps['sandboxMap'].layer.addGeoviewLayerByGeoCoreUUID function
3. Add 3 uuid quickly
4. See order is not always kept

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

**Comment by MLAuger** [comment]
I experienced a similar problem with the web service of this dataset: "MPMO - Major Projects, August 2019" (52baeb21-9dc2-42f7-b944-8bbe4b4b66a0).

When loaded in GeoView, the sublayer order is reorganized 1, 2 & 0. Instead of the native order 0, 1 & 2.
![image](https://github.com/user-attachments/assets/6ca3dc5e-6c13-488b-942d-bbfdf2cef105)
![image](https://github.com/user-attachments/assets/5c36198c-100d-4a01-b2ad-70452e15764b)

In RAMP, the order is respected:
![image](https://github.com/user-attachments/assets/e2ea34a3-f42a-4c41-b609-8161b9e632fb)
