### ISSUE TITLE
[BUG] Legend image icon ratio is not respected for WMS layers in the Layers tab.

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Legend icon image ratio is not respected for WMS layers in the Layers tab although it is in the Legend tab. For layers with only one item, the icon is compress looking weird. 
![image](https://github.com/user-attachments/assets/6070c82d-e9f6-4aa6-95e6-535fb781e6a6)

Same items in the Legend tab: 
![image](https://github.com/user-attachments/assets/ce59ff97-2f8e-4625-9cb1-8480f9d0b759)

UUID of BC Parks: 1130248f-f1a3-4956-8b2e-38d29d3e4af7

### Expected Behavior

Legend icon should be identical has in the Legend tab.

**Comment by jolevesq** [comment]
For BC park, right behavior is the one on legend panel. When we open item in layers we see there is only one item. In the icon stack of the layers panel, item is duplicated to fill the box. This is not right.
