### ISSUE TITLE
Evaluate missing UI

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#256]
From this site. https://maps.canada.ca/czs/index-en.html, evaluate missing pieces of UI available from our UI api offering and created issues for each one of them.

**Comment by yass0016** [comment]
TextField, select (dropdown)

**Comment by maxmalynowsky** [comment]
- Stepper 
- Step
- StepLabel
- StepContent
- Typography
- InputLabel
- FormControl
- MenuItem

**Comment by jolevesq** [comment]
Not specifically for this site but Calendar would be needed.
