### ISSUE TITLE
Migrate Material UI from v4 to v5

### ISSUE THREAD

**Issue by codey-codes** [Canadian-Geospatial-Platform/GeoView#258]
Currently we are using v4 of Material UI. Switching to v5 for up-to-date code.

**Comment by ychoquet** [comment]
Already have a working version. I have to sync it with upstream/develop

**Comment by jolevesq** [comment]
@yass0016 @codey-codes Can we close PR as already been merged. If there is still issue they should be recreated in a new issue

**Comment by yass0016** [comment]
@jolevesq can we hold on a little bit on this? I want to confirm the changes that @codey-codes did after the merge we did from @ychoquet. I will update this once I confirm the changes. Either I ask @codey-codes to pull latest changes and we create a new PR linked to this issue or we close this and create a new issue and apply the changes @codey-codes made.

**Comment by yass0016** [comment]
I had a look at the latest changes done by @codey-codes, we can close this one @jolevesq, we need to create a new issue that will solve layout and theming issues. Maybe a step was missed while the upgrade was done that caused theming to stop working.
