### ISSUE TITLE
[BUG] Data Table icons do not reflect layers symbology

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The icons visible in the data table are not coherent with the symbology of a layer. Currently it takes the symbol of the first class available in the layer and spreads it all across the table.

![image](https://github.com/user-attachments/assets/7ed9a68b-9b10-498d-a10d-87959fec481f)

![image](https://github.com/user-attachments/assets/0473f635-3e7c-47d8-9615-8419b7ab26e2)

Source UUID: 472ef86d-7f7c-423b-a7d2-b6f92b79fd6d

### Expected Behavior

The icon of each item should represent their respective symbology class as in RAMP:
![image](https://github.com/user-attachments/assets/f60c7aae-05c7-4318-aedf-c6aed290b2c1)

**Comment by jolevesq** [comment]
This behavior is for all esriDynamic layer. Vector layers are fine/
