### ISSUE TITLE
An issue running the core when using older chrome versions

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/GeoView#259]
It was reported to me that using an older version of Chrome causes the project not to load and gives blank page

**Comment by jolevesq** [comment]
@yass0016 Do you have version number?

**Comment by yass0016** [comment]
@jolevesq Yes, they were running version 79, I also think we should support at least IE11 since it doesn't load as well unless we are moving away from IE

**Comment by jolevesq** [comment]
@yass0016 Version 79 release date was 2019. We will have to decide how long we support old version (we are at 100). If it is a quick fix it may be ok but we should not expect to support all versions.

For IE, I would not put this a priority at the moment. We should support Edge, Chrome and Firefox. We can create an issue specific for IE but there so many bugs in IE it would take a fair amount of work. What do you think?

**Comment by jolevesq** [comment]
@yass0016 We will not support IE as some libraries we are using may have problem:

Material-UI: It no longer supports IE 11. If you need to support IE 11, check out our [legacy bundle](https://mui.com/guides/minimizing-bundle-size/#legacy-bundle).

**Comment by yass0016** [comment]
@jolevesq I agree, then no need to support it, IE will no longer be supported by Microsoft this August. We are currently support last 2 versions of Chrome, Safari, Firefox and Edge
