### ISSUE TITLE
[BUG] SERVER-DOWN 25 - Zoom to layer function behaves strangely when layer loaded in 3978 [OSDP-1801]  (25 layers)

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Two behaviors are observed when loading layers in viewer is set in 3978:

1. When loaded in 3978, "Zoom to layer" has a strange behavior : in 3978 = zooms on Winnipeg; in 3857 = zooms in the Atlantic Ocean.
2. When loaded in 3978, "Zoom to layer" has a strange behavior: in 3978 = zooms in North Dakota; in 3857 = zooms in the Atlantic Ocean

Almost all of them are WMS services.

Important: This behavior does not happen when these layers are loaded in 3857. In this situation, the Zoom to layer give coherent results.

Here are the concerned UUID:

5004eff1-6200-4c47-918f-b872e53260a3
57adb699-4c98-4694-8540-08625cab9ab9
6272b8c2-5c8b-408c-a8c8-95b27f5b59f6
5cc142ca-d9bf-43b3-8f90-3d14eac1cd7f
44d8225f-ffde-4c1a-b852-ca93df0729e3
8a7c6938-ac77-4afb-af36-a472f4d6693a
025fcebf-1b52-4013-9cd3-006ab1f00bf9
0ce538f3-65c5-4b18-8c80-1459ebae66e1
6956a8f8-4cb0-43ce-a8a4-e678fab9ccdb
ebd1f2e6-b245-47dc-a094-d65cbfc81afd
60e7157a-72ed-4017-a8db-7a0e39553e7a
0aa0cd82-993b-48e8-9524-c651a4e5ddc9
3abbdf26-7a0d-4b33-b6be-cf5303167ff2
bbff6c5f-20df-4aea-843e-10ce4e49dbcf
92e3517a-9a18-4059-81d1-69c57c2eaa0c
08ed9d99-126a-42b8-a1c6-e46f130c213e
81ffd58c-c23e-4930-bc68-cdf9179b37a2
1a560a12-9be1-49a4-971a-dbc80875a0d7
64797286-3ca5-4202-9064-a7f790321e9e
e4731a85-ffca-4112-8caf-cb0a96905778
fed6d845-b7ff-4512-8f5f-595420cc43e8
dd7d7ff3-9512-499a-ae55-56beedfbbf9c
a8b81f67-57b2-45f3-9a88-f9953d64f1a1
e3c3c580-996a-4668-8bc5-6aa7c7dc4932
9d00aa0a-a825-4804-b29b-1eff4f82a085

### Steps To Reproduce

1. Set the viewer in LCC
2. Load any of the above UUIDs
3. Go in the Layers tab, select the layer and click the Zoom to layer icon

### Anything else?

New layer from OSDP
I’ve encountered an issue with the zoom functionality for the layer with UUID: cf21aa0c-b76c-4f1f-96c1-4ef4b085b647. When I click the zoom icon in Test-R2 and GeoView, the map zooms to the northwest, despite the layer being located in the east. This causes the viewer to miscalculate where the contents of the layer should be, resulting in an inaccurate portion of the map being displayed.

Additionally, this behavior presents the viewer with half of the base map empty. This is problematic because when the map is zoomed out, that same portion is visible, indicating that something is amiss with how the zoom functionality is handling tile presentation.

When testing in Greendev, the zoom works as expected, correctly focusing on the eastern location of the layer.

Steps to Reproduce:

Open the Test-R2 ([Explorer par région](https://en-fr-test.r2.osdp.aws.nrcan-rncan.cloud/dp/fr/explorer)) or GeoView environments.

Add the layer with UUID cf21aa0c-b76c-4f1f-96c1-4ef4b085b647.

Click the zoom icon for the layer.

Observe that the map zooms to the northwest, instead of the expected eastern location, and leaves a portion of the base map empty.

Expected Behavior: The zoom should focus on the correct location of the layer to the east, without misplacing the view. The base map should display correctly without leaving large empty sections.

**Comment by Alex-NRCan** [comment]
Done some work on supporting more projections again.
GeoCore doesn't seem to be functioning well today though, bad day to test the cases.
Still, here's the status as of now.

- 5004eff1-6200-4c47-918f-b872e53260a3  _GeoCoreUUID doesn't work at all for me_
- 57adb699-4c98-4694-8540-08625cab9ab9 _GeoCoreUUID doesn't work at all for me_
- 6272b8c2-5c8b-408c-a8c8-95b27f5b59f6 _GeoCoreUUID doesn't work at all for me_
- 5cc142ca-d9bf-43b3-8f90-3d14eac1cd7f _The GeoCoreUUID works, but layer fails to load, can't test_
- 44d8225f-ffde-4c1a-b852-ca93df0729e3 _GeoCoreUUID doesn't work at all for me_
- 8a7c6938-ac77-4afb-af36-a472f4d6693a _GeoCoreUUID doesn't work at all for me_
- 025fcebf-1b52-4013-9cd3-006ab1f00bf9 _GeoCoreUUID doesn't work at all for me_
- 0ce538f3-65c5-4b18-8c80-1459ebae66e1 _GeoCoreUUID doesn't work at all for me_
- 6956a8f8-4cb0-43ce-a8a4-e678fab9ccdb _GeoCoreUUID doesn't work at all for me_
- ebd1f2e6-b245-47dc-a094-d65cbfc81afd _GeoCoreUUID doesn't work at all for me_
- 60e7157a-72ed-4017-a8db-7a0e39553e7a _GeoCoreUUID doesn't work at all for me_
- 0aa0cd82-993b-48e8-9524-c651a4e5ddc9 _GeoCoreUUID doesn't work at all for me_
- 3abbdf26-7a0d-4b33-b6be-cf5303167ff2 _GeoCoreUUID doesn't work at all for me_
- bbff6c5f-20df-4aea-843e-10ce4e49dbcf _GeoCoreUUID doesn't work at all for me_
- 92e3517a-9a18-4059-81d1-69c57c2eaa0c _GeoCoreUUID doesn't work at all for me_
- 08ed9d99-126a-42b8-a1c6-e46f130c213e _GeoCoreUUID doesn't work at all for me_
- 81ffd58c-c23e-4930-bc68-cdf9179b37a2 _GeoCoreUUID doesn't work at all for me_
- 1a560a12-9be1-49a4-971a-dbc80875a0d7 _Works, but weird data in the layer_
- 64797286-3ca5-4202-9064-a7f790321e9e _Works, but weird data in the layer_
- e4731a85-ffca-4112-8caf-cb0a96905778 _Works, but weird data in the layer_
- fed6d845-b7ff-4512-8f5f-595420cc43e8 _Works, but weird data in the layer_
- dd7d7ff3-9512-499a-ae55-56beedfbbf9c _Works, but weird data in the layer_
- a8b81f67-57b2-45f3-9a88-f9953d64f1a1 _Works, but weird data in the layer_
- e3c3c580-996a-4668-8bc5-6aa7c7dc4932 _Works, but weird data in the layer_
- 9d00aa0a-a825-4804-b29b-1eff4f82a085 _The only one that really worked well today and that I was able to fix support for its projection_

**Comment by MatthewMuehlhauserNRCan** [comment]
I think for many of these, it may not be a GeoCore issue and that there have been changes to the items / services or they are currently being updated based on the Open Canada page. 

[5004eff1-6200-4c47-918f-b872e53260a3](https://open.canada.ca/data/en/dataset/5004eff1-6200-4c47-918f-b872e53260a3) - PDF only
[57adb699-4c98-4694-8540-08625cab9ab9](https://open.canada.ca/data/en/dataset/57adb699-4c98-4694-8540-08625cab9ab9) - PDF only
[6272b8c2-5c8b-408c-a8c8-95b27f5b59f6](https://open.canada.ca/data/en/dataset/6272b8c2-5c8b-408c-a8c8-95b27f5b59f6) - PDF only
[5cc142ca-d9bf-43b3-8f90-3d14eac1cd7f](https://open.canada.ca/data/en/dataset/5cc142ca-d9bf-43b3-8f90-3d14eac1cd7f) - Empty Service: https://maps-cartes.ec.gc.ca/arcgis/rest/services/STB_AST_Dec2016/
[44d8225f-ffde-4c1a-b852-ca93df0729e3](https://open.canada.ca/data/en/dataset/44d8225f-ffde-4c1a-b852-ca93df0729e3) - PDF only
[8a7c6938-ac77-4afb-af36-a472f4d6693a](https://open.canada.ca/data/en/dataset/8a7c6938-ac77-4afb-af36-a472f4d6693a) - PDF only
[025fcebf-1b52-4013-9cd3-006ab1f00bf9](https://open.canada.ca/data/en/dataset/025fcebf-1b52-4013-9cd3-006ab1f00bf9) - PDF only
[6956a8f8-4cb0-43ce-a8a4-e678fab9ccdb](https://open.canada.ca/data/en/dataset/6956a8f8-4cb0-43ce-a8a4-e678fab9ccdb) - PDF only
[ebd1f2e6-b245-47dc-a094-d65cbfc81afd](https://open.canada.ca/data/en/dataset/ebd1f2e6-b245-47dc-a094-d65cbfc81afd) - PDF only
[60e7157a-72ed-4017-a8db-7a0e39553e7a](https://open.canada.ca/data/en/dataset/60e7157a-72ed-4017-a8db-7a0e39553e7a) - PDF only
[0aa0cd82-993b-48e8-9524-c651a4e5ddc9](https://open.canada.ca/data/en/dataset/0aa0cd82-993b-48e8-9524-c651a4e5ddc9) - PDF only
[3abbdf26-7a0d-4b33-b6be-cf5303167ff2](https://open.canada.ca/data/en/dataset/3abbdf26-7a0d-4b33-b6be-cf5303167ff2) - PDF only
[bbff6c5f-20df-4aea-843e-10ce4e49dbcf](https://open.canada.ca/data/en/dataset/bbff6c5f-20df-4aea-843e-10ce4e49dbcf) - PDF only
[92e3517a-9a18-4059-81d1-69c57c2eaa0c](https://open.canada.ca/data/en/dataset/92e3517a-9a18-4059-81d1-69c57c2eaa0c) - PDF only
[08ed9d99-126a-42b8-a1c6-e46f130c213e](https://open.canada.ca/data/en/dataset/08ed9d99-126a-42b8-a1c6-e46f130c213e) - PDF only
[81ffd58c-c23e-4930-bc68-cdf9179b37a2](https://open.canada.ca/data/en/dataset/81ffd58c-c23e-4930-bc68-cdf9179b37a2) - PDF only
[1a560a12-9be1-49a4-971a-dbc80875a0d7](https://open.canada.ca/data/en/dataset/1a560a12-9be1-49a4-971a-dbc80875a0d7) - WMS, only shows once zoomed past a certain level. Seen in Victoria, BC
[64797286-3ca5-4202-9064-a7f790321e9e](https://open.canada.ca/data/en/dataset/64797286-3ca5-4202-9064-a7f790321e9e) WMS, only shows once zoomed past a certain level. Seen in Vancouver
[e4731a85-ffca-4112-8caf-cb0a96905778](https://open.canada.ca/data/en/dataset/e4731a85-ffca-4112-8caf-cb0a96905778) WMS, only shows once zoomed past a certain level. Seen in Vancouver
[fed6d845-b7ff-4512-8f5f-595420cc43e8](https://open.canada.ca/data/en/dataset/fed6d845-b7ff-4512-8f5f-595420cc43e8) WMS
[dd7d7ff3-9512-499a-ae55-56beedfbbf9c](https://open.canada.ca/data/en/dataset/dd7d7ff3-9512-499a-ae55-56beedfbbf9c) WMS
[a8b81f67-57b2-45f3-9a88-f9953d64f1a1](https://open.canada.ca/data/en/dataset/a8b81f67-57b2-45f3-9a88-f9953d64f1a1) WMS, only shows once zoomed past a certain level. Lakes in northern BC.
[e3c3c580-996a-4668-8bc5-6aa7c7dc4932](https://open.canada.ca/data/en/dataset/e3c3c580-996a-4668-8bc5-6aa7c7dc4932) WMS, only shows once zoomed past a certain level. Anywhere in BC
[9d00aa0a-a825-4804-b29b-1eff4f82a085](https://open.canada.ca/data/en/dataset/9d00aa0a-a825-4804-b29b-1eff4f82a085) ESRI REST

**Comment by MLAuger** [comment]
Its seems all visualization services were deleted for the ECCC records of these 2 collections on December 10: 

-[ Projected change in mean temperature](https://gcgeo.gc.ca/geonetwork/metadata/eng/4283d729-dd16-4d96-9712-d61a27511ae6)
- [Projected relative change in mean precipitation](https://gcgeo.gc.ca/geonetwork/metadata/eng/22ca9127-eef9-4346-8d92-1be390df9605)
