### ISSUE TITLE
[BUG] 11 - Zoom to feature from data table does not work. [OSDP-1801]  (11 layers)

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When in the data table of a layer, if you try to click on the zoom icon nothing happens for any of the feature contained in the data table.
![image](https://github.com/user-attachments/assets/156da5b5-ccb3-42bd-952d-41cefebd8060)

Concerned UUIDs:

274ede77-27b9-46b8-96c8-4d7d4a706f08
22abff18-6f9d-4926-b7de-3a80c178bf95
21b821cf-0f1c-40ee-8925-eab12d357668
039fbd92-43c2-4805-b210-d65703712e37
622a7f72-4a00-4f9e-b04f-af6551c77db3
1c61d457-4d03-4f3a-9005-9aabb5a201bb
5c670585-97ed-4e6a-a607-30fab940ff88
2163f792-d105-4e80-8150-08b49fab20c0
cfab1711-3566-4481-aebf-292ef56b216a
6ab784be-1197-4820-8bc2-fd20da32632c
87b08750-4180-4d31-9414-a9470eba9b42

### Expected Behavior

As for other layers, when clicking on the zoom icon from the data table, the viewer should lead you to the targeted feature.

### Steps To Reproduce

1. Load any the above UUID
2. Go into the Data Table tab and load the data table
3. Click on the zoom icon for any of the feature within the loaded data table.

**Comment by DamonU2** [comment]
274ede77-27b9-46b8-96c8-4d7d4a706f08 - fixed
22abff18-6f9d-4926-b7de-3a80c178bf95 - fixed
21b821cf-0f1c-40ee-8925-eab12d357668 - no geometry returned - doesn't work in RAMP
039fbd92-43c2-4805-b210-d65703712e37 - no geometry returned - doesn't work in RAMP
622a7f72-4a00-4f9e-b04f-af6551c77db3 - fixed
1c61d457-4d03-4f3a-9005-9aabb5a201bb - no layers returned from geocore
5c670585-97ed-4e6a-a607-30fab940ff88 - no geometry returned - doesn't work in RAMP
2163f792-d105-4e80-8150-08b49fab20c0 - fixed
cfab1711-3566-4481-aebf-292ef56b216a - fixed
6ab784be-1197-4820-8bc2-fd20da32632c - wms layer, no data table
87b08750-4180-4d31-9414-a9470eba9b42 - fixed
