### ISSUE TITLE
[BUG] Style and feature info not implemented properly in pygeoapi processes

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#2599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The style from the config in pygeoapi processes is not applied to the data, and no feature info is shown when clicking on a feature.

### Expected Behavior

Style should be applied to features, info should be available

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/pygeoapi-processes.html
Click on "Raster Drill Process", point comes in with default style (should be red star)
Click on feature, no info in details.

**Comment by jolevesq** [comment]
Style is good now since we reinstate the dataAccessPAth
