### ISSUE TITLE
Do load test

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#26]
Leaflet is a light weight library to do mapping. It works very well with light layer where the feature are simple (not too many vertices) and when there is not too much of them.

We need to do load test with different layer (WMS, ESRI dynamic and feature) to see what are the limits
We need to do load test by adding simples geometries and see what are the limits

From the result, we need to update our documentation so we can inform user of what is the best practice or even prevent the loading of a layer who would freeze the viewer.

**Comment by yass0016** [comment]
See this link for reference,
https://medium.com/@ThomasG77/rendering-points-in-web-mapping-the-match-f0d8b30664fb
