### ISSUE TITLE
Improve gitignore file

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#29]
Add missing files to gitignore.

We should remove:
- [ ] bundle analyzer.html and bundle-size-analyzer.log. There are created by the build process.
- [ ] .DS_Store created by Mac
- [ ] ...

**Comment by yass0016** [comment]
`# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*`

Can you replace it with this?
