### ISSUE TITLE
Add Geo.ca icon to attribution

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#295]
Check if we should add a GEo.ca icon to attribution we links to Ge.ca website. See if it should go to viewer. Because GeoView may be use outside of Geo.ca it would be a way to make a link.

**Comment by yass0016** [comment]
@jolevesq if we have a footer bar, I should have the ability to add content to it with an API call, just like the navbar and appbar.

**Comment by jolevesq** [comment]
@yass0016 I think you are right, we would need a footer component (always there, we can't remove) who will contain at fix position
- Attribution
- Scale
- Position / elevation (this can be remove for static map and mobile)

Plus like you said info can be added. Should it only be text? From discussion we had, transparency is not good with clickable element...

**Comment by jolevesq** [comment]
Added to version appbar control
