### ISSUE TITLE
Refactor layers to have accessible functions from each layer

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/GeoView#296]
Currently when accessing functions like getCapabilities we are accessing it from leaflet wms, instead refactor the layers to have our own functions

**Comment by jolevesq** [comment]
@yass0016 Should it be covered by #285?

**Comment by yass0016** [comment]
@LarryWang888 For layers can we make it an object instead of an array? This will also improve the performance when updating / deleting the layer

https://github.com/Canadian-Geospatial-Platform/GeoView/blob/92af5dd80906100320f1f7c3d130d98e4bb69b25/packages/geoview-core/src/geo/layer/layer.ts#L32

**Comment by jolevesq** [comment]
@yass0016 So layer is object and map as an array of layers?

**Comment by LarryWang888** [comment]
Hided map object from each layer
