### ISSUE TITLE
Fix issues with the new upgrade that was made to Material UI

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/GeoView#297]
Currently there are issues loading custom styles with theming after the upgrade was done from mui 4 to mui 5.

**Comment by jolevesq** [comment]
Another issue with dialog box for WCAG navigation. Foe the moment the code is in the focus component. It should migrate to UI suction and only keep logic in focus component

**Comment by yass0016** [comment]
> Another issue with dialog box for WCAG navigation. Foe the moment the code is in the focus component. It should migrate to UI suction and only keep logic in focus component

@codey-codes is working on the modal at the moment, he will move focus trap and move the ui to the ui section
