### ISSUE TITLE
Attribution is getting too long

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#31]
Attribution at the bottom of the map is getting too long when we add layers who add their attribution inside this room. The result is the coordinates and scale section is written over. Possible solution:

* Put a max width to the div so there is no overlap
* Remove attribution added by layers

**Comment by yass0016** [comment]
I agree, best solution would be to give it a width of at least 60% and make the height auto. This will allow us to see the full attribution if the mouse hovers over it

**Comment by jolevesq** [comment]
Attribution is also under the appbar. We need to push it to the right so it is not hidden.
