### ISSUE TITLE
MUI TextField Component not functional

### ISSUE THREAD

**Issue by maxmalynowsky** [Canadian-Geospatial-Platform/GeoView#313]
Loading the [MUI Text Field Compoment](https://mui.com/components/text-fields/) into a panel results in an input that loses focus after typing in one letter. Users must either copy/paste the content in, or click to regain focus after entering each letter.

**Comment by yass0016** [comment]
Will need to check this while fixing issue #301
@maxmalynowsky is it the same styling issue or it's a panel issue like issue #312 ?
