### ISSUE TITLE
Type usage rectification on the marker cluster feature

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/GeoView#370]
Some section of the code didn't use the types appropriately. Did not correct everything, but it a starting point.
Type usage rectification is on the marker cluster feature of GeoView.

**Comment by jolevesq** [comment]
@ychoquet @yass0016 Can Prettier or ESLint would be able to track the problem so when developers PR their code we can ask them to solve it before the merge?

**Comment by yass0016** [comment]
@ychoquet can you give an example of where in the code types were missed?
