### ISSUE TITLE
ESRI Dynamic entries issues

### ISSUE THREAD

**Issue by maxmalynowsky** [Canadian-Geospatial-Platform/geoview#389]
For ESRI Dynamic Layers, `layer.getLegendJson()` function does not return entries for layer groups. In the following example, entries `[0, 6, 11, 16]` are all missing, and do not show up in the layers panel, even though they are added to the map correctly.

<img width="472" alt="Screen Shot 2022-03-31 at 10 40 55" src="https://user-images.githubusercontent.com/4202166/161082227-717cfbc4-512b-41d1-9f8b-9a0d0640f6a3.png">

**Comment by jolevesq** [comment]
Tested it with 2 group id and it works
