### ISSUE TITLE
Extract time dimension from temporal layers

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#408]
Add function to abstract layer class to extract temporal dimension.

Add to WMS layer time a function to extract dimensions parameters. This function will be use in the range slider to setup the slider object.

EsriFeature - esriDynamic
WFS ???
OGC Feature API ???

We need to follow ISO date format and OGC specification. We need to support continuous (start/end) 2 handles, continuous (start/end) one handle, discrete one handle.

**Comment by ychoquet** [comment]
I will work on this issue when I get to the child class of the class hierarchy.
