### ISSUE TITLE
Super class for vector layers

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#441]
Leaflet treats GeoJSON, WFS, OGC Feature API vector layers in a similar way. Create a super class to extend to all those layers with common function for display, style, filter, ...

**Comment by yass0016** [comment]
Use https://json-schema-faker.js.org/ to validate schema. Helpful for generating a sample object from the schema and creating the types

**Comment by ychoquet** [comment]
Please, confirm that there is no overlap whit the following assigment:
Saleh is working on the schema;
Yves is working on the super class.

**Comment by yass0016** [comment]
@ychoquet there is no overlap, all the modifications I did has already been merged to develop, you can reference this with your current work on the super class

**Comment by jolevesq** [comment]
Done with the refactor
