### ISSUE TITLE
Style Footer Tabs component and Add Config in the schema

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/geoview#497]
- [ ] Add styling to the footer tabs component
- [ ] Add properties in the schema to enable/disable the footers component just like other components such as north-arrow, overview-map, appbar, navbar
- [ ] Add properties in the schema to configure the footer tabs component, maybe allow it to start either expanded, collapsed

**Comment by jolevesq** [comment]
Will be deal by #499
