### ISSUE TITLE
Use GitHub Actions to build demo site in repo

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geoview#507]
Consider using GitHub Actions to build and deploy the demo application in THIS repo on a PR merge. 

Example here: https://github.com/RedCrewOS/api-sdk-creator-js/blob/main/.github/workflows/ci.yml

**Comment by jolevesq** [comment]
@jvanulde We added some github action: https://github.com/Canadian-Geospatial-Platform/GeoView/tree/develop/.github/workflows to do automatic deploy from PR request and PR merge. Does this seems right to you?
