### ISSUE TITLE
Update Readme from Latest Schema

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#512]
Make sure README uses the latest schema and informations.

At the same time, review the md files.

Inside md files, explain the typeguard and how to implement a new layer type from config to format.

Inside one of the md file explain the type & operator:
Yves comment:
Sometime you define the the typeProps with extend and here with &.... what is the difference?

This define the type TypeTextFieldProps as being a TextFieldProps and also an object with an optional mapId attribute of type string. This being said, I'm not sure it is needed in this context. For more information, see [intersection-types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#intersection-types)

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/512?planning-poker) with Zenhub @ychoquet

**Comment by jolevesq** [comment]
This will not be done
