### ISSUE TITLE
Use config-validation for auto completing all kinds of GeoView layers

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/geoview#528]
GeoView layers have fields with a default value and also fields that can have only one value. The code that creates the configuration of GeoView layers must use the doExtraValidation method coded in the ConfigValidation class (file: geoview-core\src\core\utils\config\config-validation.ts) to take advantage of the auto-completion side effect of the method. This will avoid harcoded values all over the code. This will allow us to centralize the definition of single value or default fields in one place.

**Comment by jolevesq** [comment]
Apply the same method to the ```UUIDmapConfigReader.getGVlayersConfigFromUUID(mapId, requestUrl);``` from url-config-readers.ts

A lot of error are introduced in the console.

**Comment by ychoquet** [comment]
Part of the solution was coded. Config.configValidation is now public and we can validate the geoview layer config using the  Config.configValidation.validateListOfGeoviewLayerConfig method. The only piece missing is the schema validation for geoview layer config wich is a sub validation of the currently implemented schema validation.

**Comment by jolevesq** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/528?planning-poker) with Zenhub @ychoquet
