### ISSUE TITLE
Add a flag to layers configuration items

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#538]
The legend/legend component will use this flag to know if the items can be added. i.e. is visibility is "disable", the control will not be added to the component.

**Comment by ychoquet** [comment]
Is it possible to add more information to this issue. There is already a visibility flag to the config. In what this issue differs from the current implementation?

**Comment by ychoquet** [comment]
Ok, I see. The 'is disable' flag is missing.
