### ISSUE TITLE
Support GeoJSON multi-polygons standard

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#550]
OSDP is following the GeoJSON standard for geometry collection and multi-polygon. The current RAMP viewer with the ESRI API is not able to load this format properly.

Test in GeoView and make the needed modifications to load the GeoJSON standard properly.

https://fgp-pgf.atlassian.net/browse/OSDP-1148
https://fgp-pgf.atlassian.net/browse/OSDP-1145
https://fgp-pgf.atlassian.net/browse/OSDP-1189

**Comment by jolevesq** [comment]
__1189__

Because we are now getting close to Feature Freeze on March 25th and we are using this capability prominently in R6, we need this addressed ASAP.

The proposed solution to display multiple polygons within RAMP was using a geoJSON file that utilized the mulitpolygon format rather than the GeometryCollection per standard RFC-7946 due to potential limitations in the RAMP implementation of geoJSON support, whose fix is being explored with ECCC.  For reference, the polygon standard can be consulted here: [RFC 7946: The GeoJSON Format](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6) 

However, this solution does not work for overlapping polygons, as noted in this example: Example: https://green.dev.osdp.aws.nrcan-rncan.cloud/dp/en/search/metadata/NRCAN-GEOSCAN-1-305398.  Rather than displaying the polygons in their entirety, when they are overlapping they are subtracted, creating negative space or “holes”, whether they are contained within another or simply intersect.  For illustration, the above example renders this way in RAMP. (the geojson file that is being displayed is also attached to this ticket).

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/3472990/bc2ac012-12c0-4af6-88c8-ad4a89101c3e)

The same file renders in a similar way using online viewers such as [geojson.io | powered by Mapbox](http://geojson.io/) , confirming that the issue is with our proposed representation since they both result in the same issue.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/3472990/c85c3faa-668b-4a70-ab84-bbc1f823a40b)

We require a solution that properly displays full polygons whether they are overlapping or not, within the same file that meets all the display criteria previously covered.  e.g. clicking on any polygon for the same record pops the same metadata panel, clicking on one of the polygons highlights them all,  proper shading and outline, etc.

**Comment by jolevesq** [comment]
__1145__

We’re in the process of implementing the geoJSON representation we discussed for the OSDP datasets, collections, and publication extents/polygons, and have been learning more about the standard RFC-7946.  In doing so, we think that we should be using a subtly different syntax than was in your test example, and would like your advice @Johann Levesque.

In the test example, we had syntax for 2 polygons that looked like this - where we grouped both under the same coordinates.  When we clicked on one polygon in RAMP, all polygons were highlighted which is an important feature we need to keep.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/3472990/a42c300c-ab99-4227-8f22-cd30d3976cef)

A learning from Leandro’s analysis as he seeks to implement, is that the paired polygon structure above is usually associated with representing multi-polygons with holes (e.g. Outer rings are counter-clockwise, inner clockwise) and therefore our proposed implementation may not totally align with the standard.  The section of the standard that got us thinking was section 3.1.6 where it states: “For Polygons with more than one of these rings, the first MUST be the exterior ring, and any others MUST be interior rings.  The exterior ring bounds the surface, and the interior rings (if  present) bound holes within the surface.”  

Digging deeper, we think that a more flexible and consistently interpreted approach within the standard would be to represent multiple polygons within a GeometryCollection as depicted in the example below.  It would also allow for greater flexibility should we wish to expand the options later.

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/3472990/8336677c-4467-441e-8612-ac94402ffd81)

In your opinion would the proposed approach above work to represent 1 or more possibly overlapping polygons, and when I click on one will RAMP highlight them all?  Could you swap out your test example with a geoJSON that is formed like this and do a quick check that it works as expected, please and thanks?

Please advise once you can comment, as current related delivery activities are waiting on this update.

**Comment by DamonU2** [comment]
This works as desired in geoview with features set up as 'MultiPolygon'.
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/63123585/8c4fc43a-777c-4248-9e4b-96723ccab98d)
With:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "Province": "Multi",
        "creationDate": "14/02/2020T19:00:00-05:00"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [-89, 54],
              [-85, 55],
              [-85, 52],
              [-89, 52],
              [-89, 54]
            ]
          ],
          [
            [
              [-90, 52],
              [-84, 53],
              [-84, 50],
              [-90, 50],
              [-90, 52]
            ]
          ],
          [
            [
              [-73, 50],
              [-73, 45.5],
              [-74.25, 45.5],
              [-74.25, 50],
              [-73, 50]
            ]
          ],
          [
            [
              [-115, 55],
              [-110.25, 55],
              [-111, 49.5],
              [-114, 49.6],
              [-115, 55]
            ]
          ]
        ]
      }
    }
  ]
}

```
