### ISSUE TITLE
Update Theme to MUI v5

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#556]
MUI has been updated to v5 but some section of the theme are not working anymore like font familly...

Investigate all modification.

Sample for typo: https://github.com/mui/material-ui/issues/28633

**Comment by dayc-mapdev** [comment]
@jolevesq What is the default font family we want to use? I see both Roboto and Monserrat being used in different places, with 'Helvetica', 'Arial', sans-serif as alternates.

**Comment by dayc-mapdev** [comment]
makeStyles has been deprecated in v5 - https://mui.com/system/styles/basics/

- configure base MUI components in theme.tsx [see here](https://mui.com/material-ui/customization/theme-components/#global-style-overrides)

- use sx for our own components, pulling from theme where necessary eg.` sx={{ color: 'text.primary' }}`
