### ISSUE TITLE
Issue when loading layers

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#564]
When loading layers on test.html page, we have this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'setVisible')
    at e.readyCallback (test.html:66:54)
    at e.callInitCallback (api.ts:110:34)
    at e.loadPlugin (plugin.ts:325:7)
    at e.loadPlugins (plugin.ts:336:12)
    at map.tsx:108:7
    at api.ts:93:21
```

There is something with the time-order of layer creation who creates a call to a function who does not already exist.

**Comment by ychoquet** [comment]
The geoview layer creation uses Promises. We must incorporate a flag on each geoview layer that will be use to decide that we can call the cgpv.init method only when all geoview layers are properly loaded.

**Comment by jolevesq** [comment]
Related #631
