### ISSUE TITLE
Build events for reusable legend component

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#576]
Build the event listener for the legend reusable component. See how the ```registerToPanel``` event is made in ```abstract-geoview-layers``` file. The event should return in his payload the React HTML component to add to a panel or direclty on the HTML page.

**Comment by ychoquet** [comment]
Note that registerToPanel was renamed to registerToLayerSets and the event managment (LegendsLayerSet) was done at the same time we did it for the FeatureInfoLayerSet.

**Comment by ychoquet** [comment]
No, we still need to work on this issue. See my comment on issue 615.

**Comment by ychoquet** [comment]
No, but #601 does.
