### ISSUE TITLE
Add field info to vector and ESRI dynamic layer

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#587]
Add to the metadata of the layer the fields information available (name, alias, type, ....).This will be reuse by the details and table component.

We should add the legend canvas element for the item

**Comment by ychoquet** [comment]
The code already reads these parameters in the processFeatureInfoConfig method of esri-dynamic.ts

**Comment by ychoquet** [comment]
Implementation doesn't take into account the alias values provided. Correction has been applied to all layers that use aliases.
