### ISSUE TITLE
Create the ability to load a plugin using a react component

### ISSUE THREAD

**Issue by yass0016** [Canadian-Geospatial-Platform/GeoView#61]
Right now creating a plugin to load content from outside such as creating a content for a panel is done by passing HTML elements, add the ability to create the content using a react component so that if a change happens in the state the content will update automatically

**Comment by jolevesq** [comment]
To show it working, we should create a plugin who will listen to map addLayer event. when a layer is added, it will add label with his name on it and the layer type. It will also add a button who, when click will remove the layer.

This will use a react component syntax form the plugin. when loaded it will create a component from who will be link with the map and the other component.
