### ISSUE TITLE
Update them dark vs light

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#610]
For the momoent we have in our configuration a theme paramter with 'dark' or 'light'. I do not think this paramter is use at the moment. Make it work and create the light theme (looks like the old one - white with black text). At the same time repair the dark theme because some panel content are not visible properly in the some panel content. Make sure que al text and border are light.

Does all the component needs modification or it can be manage in the theme file? If the issues is too big, we may split. 

At the same time it may be related to #556

**Comment by dayc-mapdev** [comment]
Should the appBar also use the light/dark theme? If so lets create a new issue for that one
