### ISSUE TITLE
Esri Dynamic icon not visible

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#614]
Fropm the getLegend response, the ESRI Dynamic points icon are not visible. These icons are generated in a canvas from their base64 values. The layers.html sample (GeoJSON) is working with a base 64. Invertigate.

**Comment by jolevesq** [comment]
@ychoquet Does #620 solve this issue?

**Comment by ychoquet** [comment]
Yes!
