### ISSUE TITLE
Add simple core basemap switcher

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#64]
We should have a core basemap switcher to use our default basemap. The switcher will be able to even switch projection from LCC to WM.

**Comment by yass0016** [comment]
Is this related to issue #50 ?

**Comment by jolevesq** [comment]
Not really the #50 will be a highly configurable plugin. When use, it will replace this core basemap switcher. So by default, this one is active. We will need a new parameter in the configuration object for switcher: true - false

**Comment by jolevesq** [comment]
This one should be more like google map base switcher. Lightweight and launch by nav bar maybe. The other one #50 will be launch by app bar or nav bar panel but  with full customization.
