### ISSUE TITLE
Create sample pages

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#7]
Create different sample pages to showcase our different use cases

Use Cases
1.	Use it as map display from metadata web presence page to show layer extent
2.	Use it as map display from metadata web presence page to show layer like a thumbnail
3.	Use it as geo search tool to do a spatial search for metadata from geoCore API
4.	Use it as simple viewer to with legend to explore data

Functionalities

Use case 1: Show extent
a.	LCC basemap and projection
b.	Add graphic for the extent

Use case 2: Show layer like thumbnail
a.	LCC or Web Mercator basemap and projection
b.	Add layer (GeoJson, WMS, Esri (dynamic and feature)

Use case 3: Geo Search
a.	LCC or Web Mercator basemap and projection
b.	Zoom in, Zoom out, Fullscreen
c.	Scale, Mouse position, Overview map
d.	Get extent from map extent (add draw later)
e.	Link to Geo Search API to add results
f.	Bilingual and WCAG

The remaining use case would need more development before creating a functional use cases
Use case 4: Simple viewer 
a.	LCC or Web Mercator basemap and projection
b.	Zoom in, Zoom out, Fullscreen
c.	Scale, Mouse position, Overview map
d.	Legend (visibility, opacity, graphic legend)
e.	Bilingual and WCAG

**Comment by jolevesq** [comment]
We need to organize our sample page. We should many pages to show different situation like the 4 use case we have plus one for language (en-fr), one for all the different basemap, one for the add element on map, one for the plugin link, ...

We will have to check how Webpack will inject everything in all the pages, not only index.html

**Comment by jolevesq** [comment]
* Landing page
     * Basemap (show different basemaps (transport-label-shaded : LCC, simple-label: LCC, just Shaded: LCC)
     * Projection (show one basemap + 1 layer in LCC and WM)
     * Language (one map English, one map French .... no layer only basemap)
     * Responsive (3 maps, one for every threshold device size to showcase the difference) 
     * Layers (one map with all the layer type (WMS, Esri feature, Esri dynamic, GeoJSON). Have the add / remove geooJSON function
     * Events (one map with the event who refresh map center on map move)
     * Vectors (all vector functions)
     * Plugins (all plugins functions) 
     * Other ideas????

**Comment by yass0016** [comment]
For this I suggest looking at the webpack.common.js file, look at 

new HtmlWebpackPlugin({
            template: './public/index.html',
            title: 'Canadian Geospatial Platform Viewer',
            inject: 'head',
            scriptLoading: 'blocking',
        }),

We should be able to pass multiple HtmlWebpackPlugin with different HTML files, just create the files in /public

**Comment by jolevesq** [comment]
All samples are done. Next one will be done on a case by case basis
