### ISSUE TITLE
Load flood in cluster page

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#772]
Add a map to demo flood data in cluster page: https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/historical_flood_event_en/MapServer

**Comment by DamonU2** [comment]
Features in this flood layer are esriGeometryMultipoint, which are not working with clustering. Might just need a simple removal of "Multi", similar to the MultiPolygon fix.
