### ISSUE TITLE
Add export to navigation toolbar and app bar

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#796]

**Comment by DamonU2** [comment]
Steps for this, as per my understanding:

- move functions into utilities
- move export button to nav bar, with an option in config: default to on?
- button opens template, with options for PNG or PDF, and which elements to include
  - elements: title, legend, scale, north arrow
  - text box for description to go in footnote

@jolevesq Does this sound right? Anything else?
