### ISSUE TITLE
Improve app startup component selection

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#8]
For the moment, the app starts when the page load. The script will loop trough the divs with class 'llwb-map'. Those divs contains configuration like projection, zoom and center point, language, layers....

We need to add 2 other type of loading

**Load from url config**
When the page load, it reads the url for configuration and apply it the div with 'llwb-map' on the page. The url will contains the same type of information https://....ca?b=3857&z=4&c=50;-75&keys=45we-54sf-r25w-52ee;.....

* b for the basemap projection, z and c for the initial extent
* Keys will be a list of layer uuid to add. The viewer will tehn call the catalog to get all the needed configuration to add all the layers listed in the keys element.
* The language will be derive from the page
* ~Only layers inside Web Presence catalog can be added this way~ 

**Load from a function call**
Call the app and pass the needed configuration and div on the map to create the map inside. The configuration will not accept keys. It will be as the same format as the one provided trough the inline div configuration or the configuration file schema.

**Load from a configuration file**
Instead of having a JSON object in data-leaflet. have a url to link to a JSON file who holds the configuration. The config from the file may be more complex and follow a schema.
```
<div
    id="mapLCC"
    class="llwp-map"
    data-leaflet="https:\\.....\my-config-fr.json"></div>
```

**Comment by jolevesq** [comment]
For every core component or core packages, each one of them must configure itself with default value from schema so if no config file provided, it will load the default.

Can we say the config naming and  location should be....
"name of core config"-"name of package".json and should be located at the same place as the core config.

myconfig.json
myconfig-layers-panel.json

For external packages, the info will be in core config.

**Comment by jolevesq** [comment]
@yass0016 Yes, you are right. The map div needs to exist and all viewer js and css files (core and packages) needs to be added to the page

**Comment by yass0016** [comment]
A schema will be created for the core, and for each of the corePackages.

The core will have default values coming from the schema. **A user can provide their own config in multiple ways**. If the config passed by the user matches the schema, the user's provided values will overwrite the default values.

The config that the user will provide will be a JavaScript Object.

Ways the user will be able to provide the config 
[**- By providing parameters in the URL**](####by-providing-parameters-in-the-url)
[**- By providing a json file url in the div in the data-config-url attribute**](####by-providing-a-json-file-url-in-the-div-in-the-data-config-url-attribute)
[**- By providing the config object inline in the div in the data-config attribute**](####by-providing-the-config-object-inline-in-the-div-in-the-data-config-attribute)
[**- By providing the config object in a function call in the init function**](####by-providing-the-config-object-in-a-function-call-in-the-init-function)

### By providing parameters in the URL
A user can provide a URL with search parameters for the config properties. This is useful for sharing links of certain configurations. An example link will look like
`
http://example.com/map.html?p=3978&z=12&c=45,75&l=en-CA&t=dark&b={id:transparent,shaded:true,labeled:true}&keys=111,222,333,123

z is for zoom level
p is for projection (currently supported values: 3857 and 3978)
c is for center (an array of two elements, represents latitude and longtitude)
l is for language (currently supported values: en-CA, fr-CA
t is for theme (currently supported values: dark, light)
b is for basemap options (an object with three properties, id, shaded, labeled)
keys is for layer uuid keys (the keys will match keys in the catalog, can be comma seperated)
`

When the page loads with the provided URL search parameters, the app will look for a map with the **llwp-map** class. If a map is found, it will check if the map div element contains **data-shared="true"**. If the **data-shared** value is true, it means that the map will load the configurations from the url search parameters, if **multiple maps** are loaded in the page and all of them have the **data-shared** attribute then all of those maps will use the same URL parameters config.

### By providing a json file url in the div in the data-config-url attribute
A user can also provide a URL for a json file with the config object and pass it in the map div element in the **data-config-url** attribute. An example of this

```js
<div
    id="mapWM"
    class="llwp-map"
    data-config-url="https://example.com/my-config.json"
></div>
```

The content of the config must match the schema, an example of the object in the json file:

```json
{
  "map": {
    "interaction": "dynamic",
    "initialView": {
      "zoom": 12,
      "center": [45, 75]
    },
    "projection": 3978,
    "basemapOptions": {
      "id": "transport",
      "shaded": true,
      "labeled": true
    },
    "layers": []
  },
  "theme": "dark",
  "appBar": {
    "about": "# An example of a markdown"
  },
  "components": ["appbar", "navbar", "northArrow"],
  "corePackages": [
    "overview-map",
    "basemap-switcher",
    "layers-panel",
    "details-panel",
    "geolocator"
  ],
  "externalPackages": [],
  "language": "en-CA"
}
```

### By providing the config object inline in the div in the data-config attribute
A user can also provide the same config above in the **data-config** attribute of the map div element as inline

An example of this:

```html
<div
    id="UC1"
    class="llwp-map"
    data-config="{
                    'map': {
                        'interaction': 'dynamic',
                        'initialView': {
                            'zoom': 12,
                            'center': [45,75],
                        },
                        'projection': 3978,
                        'basemapOptions': {
                            'id': 'transport',
                            'shaded': true,
                            'labeled': true
                        },
                        'layers': [],
                    },
                    'theme': 'dark',
                    'appBar': {
                        'about': '# An example of a markdown'
                    },
                    'components': ['appbar', 'navbar', 'northArrow'],
                    'corePackages': ['overview-map', 'basemap-switcher', 'layers-panel', 'details-panel', 'geolocator'],
                    'externalPackages': [],
                    'language': 'en-CA'                                    
                }"
></div>
```

_Note: if user provides both **data-config** and **data-config-url**, in the same div element then the **data-config** configurations will overwrite the config coming from the json file_

### By providing the config object in a function call in the init function
A user can also provide the same config object in a function call after the **init** function has been called

An example of this:

```html

<div
    id="mapWM"
    class="llwp-map"
></div>

<script>
cgpv.init(function() {
    cgpv.api.map('mapWM').loadConfig({
        map: {
            interaction: 'dynamic',
            initialView: {
                zoom: 12,
                center: [45, 75],
            },
            projection: 3978,
            basemapOptions: {
                id: 'transport',
                shaded: true,
                labeled: true,
            },
            layers: [],
        },
        theme: 'dark',
        appBar: {
            about: '# An example of a markdown',
        },
        components: ['appbar', 'navbar', 'northArrow'],
        corePackages: ['overview-map', 'basemap-switcher', 'layers-panel', 'details-panel', 'geolocator'],
        externalPackages: [],
        language: 'en-CA',
    });
});
</script>

```

**Comment by yass0016** [comment]
- [ ] Load map config from url params
- [ ] Load map config from function call
- [ ] Load map config from inline div
- [ ] Load map config from json file provided by url
- [ ] Validate config against schema
- [ ] Load core components config and validate against their own schema
