### ISSUE TITLE
Move temporal dimension on geoview instances

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/geoview#804]
The time dimension has been added in the layerEntryConfig object. So far, most of the properties of the layerEntryConfig object have a mapping to the schema entries. There are some exceptions, but this is to chain the entries together. The schema does not contain a definition for the temporalDimension property. We should place this property on the instances of the GeoView layers to avoid breaking the mapping rule between the schema and the configuration objects.

**Comment by jolevesq** [comment]
@ychoquet Is this part done with ESRI?
```
/** ***************************************************************************************************************************
 * This method will create a Geoview temporal dimension if it exist in the service metadata
 * @param {TypeJsonObject} esriTimeDimension The ESRI time dimension object
 * @param {TypeEsriFeatureLayerEntryConfig | TypeEsriDynamicLayerEntryConfig} layerEntryConfig The layer entry to configure
 */
export function commonProcessTemporalDimension(
  this: EsriDynamic | EsriFeature,
  esriTimeDimension: TypeJsonObject,
  layerEntryConfig: TypeEsriFeatureLayerEntryConfig | TypeEsriDynamicLayerEntryConfig
) {
  if (esriTimeDimension !== undefined) {
    layerEntryConfig.temporalDimension = api.dateUtilities.createDimensionFromESRI(Cast<TimeDimensionESRI>(esriTimeDimension));
  }
}
```

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/804?planning-poker) with Zenhub @ychoquet
