### ISSUE TITLE
Export not working with XYZ source

### ISSUE THREAD

**Issue by DamonU2** [Canadian-Geospatial-Platform/geoview#805]
CORS issues are not allowing maps with XYZ layers to be exported - cross origin causes canvas to be tainted, which disallows use of `toDataURL()`

**Comment by jolevesq** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/805?planning-poker) with Zenhub @DamonU2 @ychoquet

**Comment by DamonU2** [comment]
This may just be an issue with the one tile source we are using, trying it with a few other sources after adding           
```
if (layerEntryConfig.source.crossOrigin) {
            sourceOptions.crossOrigin = layerEntryConfig.source.crossOrigin;
          } else {
            sourceOptions.crossOrigin = 'Anonymous';
          }
```
back should be a start.
