### ISSUE TITLE
[BUG] Basemap in refresh loop

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we load this demo page https://canadian-geospatial-platform.github.io/geoview/public/loading-packages.html the basemap does not refresh properly. Most of the time it came from the shaded relief basemap where there is a lot of processing to do (rockies).

### Expected Behavior

Basemap (transport, label and shaded) should load smoothly without pending request

### Steps To Reproduce

1. Load this page: https://canadian-geospatial-platform.github.io/geoview/public/loading-packages.html 
2. Open the console and look at the network tab
3. Pan the map a little by the right (problem not solved)
4. Pan the map outside the extent to the left (it solve the problem)
6. Open basemap panel, select Transport and see there is no problem
7. On the basemap panel, select transport with labels and see the problem occurs again

### Anything else?

![image](https://user-images.githubusercontent.com/3472990/214929107-e24ce273-094c-4240-b88d-f32fc3e63bd2.png)

You can see in Red on the map the basemap shaded relief and label are not updating properly. In the bottom section we can see the huge amount of pending request.

Because the problem occurs when label is there and not when only shaded, label may in problem.

**Comment by DamonU2** [comment]
The issue seems to stem from disabling cache in the developer console. I am unable to replicate the bug with the cache enabled. A minor map loading issue remains in Edge, but doesn't occur with Chrome or Firefox.
