### ISSUE TITLE
Language and projection page

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#86]
Add a page to showcase our different projection LCC - WM and another page to show translation (fr - en)

**Comment by melzeiny1980** [comment]
what would be the configuration for each projection map ?

**Comment by melzeiny1980** [comment]
Projections : 
WB ---> transport, Label and English
LCC-->---> transport, Shaded , Label and English
 languages :
English---> transport, Shaded  , Label  LCC
French ---> transport, Shaded  , Label  LCC
