### ISSUE TITLE
Map and Footer - Desktop View

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#862]
The footer-panel  is a component located at the bottom of the map were you can find useful information like legend, details, data grid, ...

![image](https://user-images.githubusercontent.com/3472990/215861169-beab555c-d5a5-4b8c-8c9c-3ac652197656.png)

Demo: https://canadian-geospatial-platform.github.io/geoview/public/package-footer-panel.html

When collapse, the real estate of the panel is minimal but when we expand it, may take a lot of space and make navigation from map to footer panel painful. We need to find the best way to navigate between both component and make it less scrolling as possible.

__Plus we think the footer panel should expand below map, min size = legend size__

__Idea 1__
Do automatic scrolling when focus is on footer and map to put the component in the visible viewport
con: automatic scrolling may not be WCAG

Other Idea...

**Comment by vgulyy** [comment]
CC: @sean-eagles

**Comment by sean-eagles** [comment]
Hi @jolevesq,  If we could move this to in progress for Vlad that would be great.

**Comment by jolevesq** [comment]
We can close as the UX is mostly done, we will now focus on the issue about UX testing
