### ISSUE TITLE
Demo Geopackages to CGDI

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#865]
Plan a demo of Geopackages functions and implementation to CGDI (see comment below)

Comment from @jvanulde 
Damon, Johann, can you please set up a meeting to demo Geopackage support in GeoView once you have something functional. Invite Graham Wilkes, Cameron Wilson, and Shannon Denny. CC Chris and I. THX!

Before we can do this we need to
- Solve multi layer loading #833
- Apply style #834
- Add Geopackages from layers panel # 863
- Test if data table and details are working

**Comment by AliyanH** [comment]
Hi we will share some lighter condensed version of the CGDI AR Data Service Kits from the [open canada website](https://open.canada.ca/data/en/dataset/2364749d-70a0-4874-956d-a636401ac5a6) here.

**Comment by jackclawlor** [comment]
> Hi we will share some lighter condensed version of the CGDI AR Data Service Kits from the [open canada website](https://open.canada.ca/data/en/dataset/2364749d-70a0-4874-956d-a636401ac5a6) here.

Light version of CGDI Data Kit for British Colombia. Includes three vector files containing information on Administrative Boundaries and First Nation Settlement locations. Size: 41,644 KB

[CGDI_BC_DataKit_Light.zip](https://github.com/Canadian-Geospatial-Platform/geoview/files/11726276/CGDI_BC_DataKit_Light.zip)

Link to original CGDI Data Kits for [British Colombia](https://open.canada.ca/data/en/dataset/2364749d-70a0-4874-956d-a636401ac5a6/resource/c9aecf08-42a0-4872-a894-af06b99c483d)

**Comment by Benjamin-Voth** [comment]
> Hi we will share some lighter condensed version of the CGDI AR Data Service Kits from the [open canada website](https://open.canada.ca/data/en/dataset/2364749d-70a0-4874-956d-a636401ac5a6) here.

Lite version of the NWT Data Kit data including 3 vector files of the boundaries and settlements:
[NWTlite.zip](https://github.com/Canadian-Geospatial-Platform/geoview/files/11726280/NWTlite.zip)


Link for original CDGI Datakit for[ NWT](https://open.canada.ca/data/en/dataset/2364749d-70a0-4874-956d-a636401ac5a6/resource/34ad2801-1dcc-4274-b5d0-db3f424ffa1a)
