### ISSUE TITLE
Legend filtering does not cover clustering

### ISSUE THREAD

**Issue by ychoquet** [Canadian-Geospatial-Platform/geoview#869]
For the moment, the implementation of the legend filtering covers only the basic layers of the vectors and esri-dynamic. Clustering of the vector layers is not covered. An analysis phase must be done to decide how we want to display the clusters before implementing the solution. Do we want to make clusters counting the features on the layer or only the visible features?

**Comment by jolevesq** [comment]
@ychoquet I would say yes, the number should the nb of visible feature from style/layer filter.

@DamonU2 How do you see this fit in your cluster implementation?
