### ISSUE TITLE
[BUG] Swiper slider bar limit

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we move the slider, sometimes, the canvas element to hide/show the layer(s) does not have the right limits. It can be wrong either left or right.

### Expected Behavior

I expect the limit of the show/hide layer(s) is always beneath the slider

### Steps To Reproduce

1. Go on package-swiper.html
2. On any of the maps, move the slider. If not able to reproduce, move it quicker

### Anything else?

Map 2
![image](https://user-images.githubusercontent.com/3472990/219035824-6cba5d83-5176-453d-83d9-f594f84bdaff.png)

Map 3
![image](https://user-images.githubusercontent.com/3472990/219036558-15d105d7-4ecd-48e7-b7e1-62d1211fb86a.png)
![image](https://user-images.githubusercontent.com/3472990/219036708-d266f1a9-f885-4589-b295-2031f8b1aa29.png)

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/901?planning-poker) with Zenhub @DamonU2
