### ISSUE TITLE
[BUG] loadMapConfig Function trigger twice

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a problem when we load the map from a function with loadMapConfig. The code is triggered twice (first for map creation from the empty div, and a second time for the map with the function div).

Problem is the viewer is lookin at the map divs on load and start map creation on them when the class "llwp-map" is there
```
<div id="LNG1" class="llwp-map" data-lang="fr"></div>
```
If the class is not there the map will never be created even if we run
```
cgpv.api.map('LNG1').loadMapConfig(config);
```

Even with inline config, i18nInstance is set twice once in French and once in English

### Expected Behavior

We should be able to create a map in any div without the llwp-map class (should be added on map creation) and the viewer should not run twice with the function call.

Repair language html page to use function loading instead of inline config.

### Steps To Reproduce

Go to language page and put a break point in app-start.tsx (i18nInstance)

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/905?planning-poker) with Zenhub @kaminderpal
