### ISSUE TITLE
[BUG] Cluster not good number

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we zoom near saint ferdinand (72W 45.5N), we have discrepancy with cluster number when you zoom out and in.

Plus clustering should disable itself when we reach a certain zoom level (level 12)

### Expected Behavior

Should be consistent.

### Steps To Reproduce

1. go to package-footer-panel.html on map 3
2. zoom to coordinates listed above
3. zoom in out and see the cluster point values (see images)

### Anything else?

<img width="255" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/3472990/219160258-774f4fee-2725-46f1-bf19-3062dd316750.png">
<img width="295" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/3472990/219160283-4faf803e-2089-4b08-8fda-48f144ade0c3.png">

**Comment by ychoquet** [comment]
This is a normal behavior resulting from the algorithm used to do the grouping. Clustering does not use a regular grid to uniformly group the icons. When the zoom level changes, some features move from one group to another which explains the change in the position of the groups and the number displayed. If you sum up the groups in a neighborhood, you should find the same number in the surroundings of the same neighborhood after a slight change of zoom.
