### ISSUE TITLE
[BUG] default label and  visible are undefined and not in styleinfo list, but layer showing on map

### ISSUE THREAD

**Issue by dennisfu** [Canadian-Geospatial-Platform/geoview#912]
**Is there an existing issue for this?**
I have searched existing issues

**Current Behavior**
When we set visibility to false with the eye and click on the first checkbox to show one item, the default layer showing up 

**Expected Behavior**
The layer by defaultlabel should be controlled as the ones in styleinfo  

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/849-turn_on_off_layer_feature/package-footer-panel.html#HUC3
2. Click on '^' icon to expand the footer panel 
3. Click on the eye icon to turn off (uncheck) all the item
4. Check any one item, the red circle icon would always showing on map with the checked one

**Anything else?**
issues #849 and PR #909
The reason:
In ESRI layer config, in the style, the default value and label are undefined instead of unknown or null, so it doesn't be loaded into the label list, also cannot find the image info to put into the icon list.

**Comment by jolevesq** [comment]
@dennisfu map 3 is the cluster map, I think toggle visibility never worked for this one. We may need to adjust configuration
