### ISSUE TITLE
[BUG] ESRI Dynamic nested group failed

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to add this layer to the layers-panel: https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer

It fails
```
react-dom.production.min.js:216 TypeError: Cannot set properties of undefined (setting 'visible')
    at legend-icon-list.tsx:99:85
    at Array.forEach (<anonymous>)
    at legend-icon-list.tsx:93:19
    at Dl (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at qi (react-dom.production.min.js:122:325)
    at Ll (react-dom.production.min.js:261:308)
    at bl (react-dom.production.min.js:243:50)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

### Expected Behavior

Should load properly

### Steps To Reproduce

1. Go to package-layers-panel.html
2. Add this layer https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer as esriDynamic
3. Select the second item (900A)

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GeoView-Web-Team-6332f4560a41153d1fefbcbc/issues/Canadian-Geospatial-Platform/geoview/920?planning-poker) with Zenhub @DamonU2
