### ISSUE TITLE
[DISCUSSION} Comment on the UX process

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#946]
Add your inputs in the Excel spreadsheet for needed viewer functionalities.

URL to come

**Comment by jolevesq** [comment]
https://docs.google.com/spreadsheets/d/1yApN9nZeTyjrcOgrQE8kah11dCRaidd9/edit?rtpof=true&sd=true#gid=670873170

**Comment by ychoquet** [comment]
Done on the slack channel.
