### ISSUE TITLE
[BUG] Add GeoJSON Layer

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to add a url [GeoJSON ](https://canadian-geospatial-platform.github.io/geoview/geojson/polygons.json) or file from the add layer function, we can't pass the second step. It says GeoJSON source is invalid

### Expected Behavior

Use to work before, we should be able to add

### Steps To Reproduce

1. Go to https://canadian-geospatial-platform.github.io/geoview/public/package-layers-panel.html
2. Try to add: https://canadian-geospatial-platform.github.io/geoview/geojson/polygons.json

**Comment by DamonU2** [comment]
I think this is an issue with the source. That link gives me a 404 (as do the other two), and polygons.json loads fine from a local file.
