### ISSUE TITLE
[BUG] PyGeoAPI 0.15.dev0 OGC API - Features not working

### ISSUE THREAD

**Issue by grefton** [Canadian-Geospatial-Platform/geoview#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to load a "collection" from PyGeoAPI version 0.15.dev0 I receive the following error in the console (see attached console log). 
Sample layer that does not work
https://132.156.9.48:30102/collections/catchment
Sample layer that does work
https://b6ryuvakk5.execute-api.us-east-1.amazonaws.com/dev/collections/lakes
[localhost-1679924408342.log](https://github.com/Canadian-Geospatial-Platform/geoview/files/11079234/localhost-1679924408342.log)

### Expected Behavior

The layer should display in the map and in the layers panel.

### Steps To Reproduce

1. Add the example layer that does work into the map config.
2. Change the map config to use the URL to the layer that does not work
3. layer does not load.

**Comment by jolevesq** [comment]
This is the error when we try to load:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getCode')
    at B (proj.js:463:39)
    at $ (proj.js:485:10)
    at z (proj.js:520:25)
    at ogc-feature.ts:222:21
    at Array.filter (<anonymous>)
    at n.value (ogc-feature.ts:168:35)
    at abstract-geoview-layers.ts:296:46
```
